/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */

#ifndef KUN_CELLULAR_CUDA_OPS_CUH_
#define KUN_CELLULAR_CUDA_OPS_CUH_

#include <stdint.h>
#include <math.h>

#if defined(__CUDACC__) || defined(__CUDA_ARCH__)
#define SDSC_CUDA_DEVICE __device__ __forceinline__
#else
#define SDSC_CUDA_DEVICE inline
#endif

SDSC_CUDA_DEVICE float sdsc_cuda_eval_primitive(
    uint8_t op,
    float gain,
    float x,
    float* state,
    float* aux
) {
    float out = 0.0f;
    float s = *state;
    float a = *aux;
    float g = gain;

    switch (op) {
        case 0: { // SDSC_OP_SENSE_0
            out = x;
            break;
        }
        case 1: { // SDSC_OP_SENSE_1
            out = x;
            break;
        }
        case 2: { // SDSC_OP_SENSE_2
            out = x;
            break;
        }
        case 3: { // SDSC_OP_SENSE_3
            out = x;
            break;
        }
        case 4: { // SDSC_OP_SUM
            out = tanhf(x * g);
            break;
        }
        case 5: { // SDSC_OP_INTEGRATE
            s = s * 0.85f + x * 0.15f;
            out = tanhf(s * g);
            break;
        }
        case 6: { // SDSC_OP_AMPLIFY
            out = tanhf(x * g * 2.5f);
            break;
        }
        case 7: { // SDSC_OP_INVERT
            out = -tanhf(x * g);
            break;
        }
        case 8: { // SDSC_OP_DAMPER
            s = s * 0.70f + x * 0.30f;
            out = s;
            break;
        }
        case 9: { // SDSC_OP_CLIP
            out = fminf(fmaxf(x * g, -1.0f), 1.0f);
            break;
        }
        case 10: { // SDSC_OP_ABS
            out = fabsf(tanhf(x * g));
            break;
        }
        case 11: { // SDSC_OP_MULTIPLY
            out = tanhf(x * g * 1.5f);
            break;
        }
        case 12: { // SDSC_OP_DIFF
            out = x - s;
            s = x;
            break;
        }
        case 13: { // SDSC_OP_SUB
            s = s * 0.60f + x * 0.40f;
            out = tanhf((x - s) * g);
            break;
        }
        case 14: { // SDSC_OP_RATIO
            s = s * 0.85f + fabsf(x) * 0.15f;
            out = fminf(fmaxf(x / (s + 0.1f), -2.0f), 2.0f);
            break;
        }
        case 15: { // SDSC_OP_THRESHOLD
            out = (x > 0.25f) ? 1.0f : ((x < -0.25f) ? -1.0f : 0.0f);
            break;
        }
        case 16: { // SDSC_OP_HYSTERESIS
            if (x > 0.15f) s = 1.0f;
            else if (x < -0.15f) s = -1.0f;
            out = s;
            break;
        }
        case 17: { // SDSC_OP_DEADZONE
            out = (fabsf(x) > 0.08f) ? (x * g) : 0.0f;
            break;
        }
        case 18: { // SDSC_OP_INHIBIT
            s = s * 0.80f + fabsf(x) * 0.20f;
            out = tanhf(x * g) * fmaxf(0.0f, 1.0f - s);
            break;
        }
        case 19: { // SDSC_OP_AND
            out = (x > 0.0f && s > 0.0f) ? 1.0f : 0.0f;
            s = x;
            break;
        }
        case 20: { // SDSC_OP_MIN_MAX
            out = fmaxf(x, s);
            s = x;
            break;
        }
        case 21: { // SDSC_OP_ACT_POS
            out = fminf(fmaxf(x * g, 0.0f), 1.0f);
            break;
        }
        case 22: { // SDSC_OP_ACT_NEG
            out = fminf(fmaxf(-x * g, 0.0f), 1.0f);
            break;
        }
        case 23: { // SDSC_OP_ACT_RESET
            out = (fabsf(x) < 0.10f) ? 0.0f : x;
            break;
        }
        case 24: { // SDSC_OP_CORRELATION
            s = s * 0.90f + (x * a) * 0.10f;
            a = x;
            out = tanhf(s * g);
            break;
        }
        case 25: { // SDSC_OP_FATIGUE
            s = fminf(2.0f, s + fabsf(x) * 0.15f) * 0.96f;
            out = tanhf(x * g) / (1.0f + s);
            break;
        }
        case 26: { // SDSC_OP_PASSTHRU
            out = x;
            break;
        }
        default:
            out = x;
            break;
    }

    *state = s;
    *aux   = a;
    return out;
}

// NVRTC JIT 动态内核代码注入模板字符串 (消除手写 CUDA JIT 源码漂移)
static const char* const SDSC_CUDA_DEVICE_OPS_SRC = R"(
__device__ __forceinline__ float sdsc_cuda_eval_primitive(
    uint8_t op,
    float gain,
    float x,
    float* state,
    float* aux
) {
    float out = 0.0f;
    float s = *state;
    float a = *aux;
    float g = gain;

    switch (op) {
        case 0: { // SDSC_OP_SENSE_0
            out = x;
            break;
        }
        case 1: { // SDSC_OP_SENSE_1
            out = x;
            break;
        }
        case 2: { // SDSC_OP_SENSE_2
            out = x;
            break;
        }
        case 3: { // SDSC_OP_SENSE_3
            out = x;
            break;
        }
        case 4: { // SDSC_OP_SUM
            out = tanhf(x * g);
            break;
        }
        case 5: { // SDSC_OP_INTEGRATE
            s = s * 0.85f + x * 0.15f;
            out = tanhf(s * g);
            break;
        }
        case 6: { // SDSC_OP_AMPLIFY
            out = tanhf(x * g * 2.5f);
            break;
        }
        case 7: { // SDSC_OP_INVERT
            out = -tanhf(x * g);
            break;
        }
        case 8: { // SDSC_OP_DAMPER
            s = s * 0.70f + x * 0.30f;
            out = s;
            break;
        }
        case 9: { // SDSC_OP_CLIP
            out = fminf(fmaxf(x * g, -1.0f), 1.0f);
            break;
        }
        case 10: { // SDSC_OP_ABS
            out = fabsf(tanhf(x * g));
            break;
        }
        case 11: { // SDSC_OP_MULTIPLY
            out = tanhf(x * g * 1.5f);
            break;
        }
        case 12: { // SDSC_OP_DIFF
            out = x - s;
            s = x;
            break;
        }
        case 13: { // SDSC_OP_SUB
            s = s * 0.60f + x * 0.40f;
            out = tanhf((x - s) * g);
            break;
        }
        case 14: { // SDSC_OP_RATIO
            s = s * 0.85f + fabsf(x) * 0.15f;
            out = fminf(fmaxf(x / (s + 0.1f), -2.0f), 2.0f);
            break;
        }
        case 15: { // SDSC_OP_THRESHOLD
            out = (x > 0.25f) ? 1.0f : ((x < -0.25f) ? -1.0f : 0.0f);
            break;
        }
        case 16: { // SDSC_OP_HYSTERESIS
            if (x > 0.15f) s = 1.0f;
            else if (x < -0.15f) s = -1.0f;
            out = s;
            break;
        }
        case 17: { // SDSC_OP_DEADZONE
            out = (fabsf(x) > 0.08f) ? (x * g) : 0.0f;
            break;
        }
        case 18: { // SDSC_OP_INHIBIT
            s = s * 0.80f + fabsf(x) * 0.20f;
            out = tanhf(x * g) * fmaxf(0.0f, 1.0f - s);
            break;
        }
        case 19: { // SDSC_OP_AND
            out = (x > 0.0f && s > 0.0f) ? 1.0f : 0.0f;
            s = x;
            break;
        }
        case 20: { // SDSC_OP_MIN_MAX
            out = fmaxf(x, s);
            s = x;
            break;
        }
        case 21: { // SDSC_OP_ACT_POS
            out = fminf(fmaxf(x * g, 0.0f), 1.0f);
            break;
        }
        case 22: { // SDSC_OP_ACT_NEG
            out = fminf(fmaxf(-x * g, 0.0f), 1.0f);
            break;
        }
        case 23: { // SDSC_OP_ACT_RESET
            out = (fabsf(x) < 0.10f) ? 0.0f : x;
            break;
        }
        case 24: { // SDSC_OP_CORRELATION
            s = s * 0.90f + (x * a) * 0.10f;
            a = x;
            out = tanhf(s * g);
            break;
        }
        case 25: { // SDSC_OP_FATIGUE
            s = fminf(2.0f, s + fabsf(x) * 0.15f) * 0.96f;
            out = tanhf(x * g) / (1.0f + s);
            break;
        }
        case 26: { // SDSC_OP_PASSTHRU
            out = x;
            break;
        }
        default:
            out = x;
            break;
    }

    *state = s;
    *aux   = a;
    return out;
}
)";

#endif /* KUN_CELLULAR_CUDA_OPS_CUH_ */
