/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */

#ifndef KUN_CELLULAR_CUDA_OPS_VJP_CUH_
#define KUN_CELLULAR_CUDA_OPS_VJP_CUH_

#include <stdint.h>
#include <math.h>

#if defined(__CUDACC__) || defined(__CUDA_ARCH__)
#define SDSC_CUDA_DEVICE __device__ __forceinline__
#else
#define SDSC_CUDA_DEVICE inline
#endif

typedef struct {
    float dx;
    float ds_prev;
    float da_prev;
    float dg;
} SdscCUDAVJP;

SDSC_CUDA_DEVICE SdscCUDAVJP sdsc_cuda_vjp_primitive(
    uint8_t op,
    float g,
    float x,
    float s,
    float a,
    float out,
    float s_next,
    float a_next,
    float dy,
    float ds_next,
    float da_next
) {
    SdscCUDAVJP ret;
    float dx = 0.0f;
    float ds_prev = 0.0f;
    float da_prev = 0.0f;
    float dg = 0.0f;

    switch (op) {
        case 0: { // SDSC_OP_SENSE_0
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 1: { // SDSC_OP_SENSE_1
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 2: { // SDSC_OP_SENSE_2
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 3: { // SDSC_OP_SENSE_3
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 4: { // SDSC_OP_SUM
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 5: { // SDSC_OP_INTEGRATE
            float dtanh = 1.0f - out * out;
            float ds_local = dy * dtanh * g;
            float ds_tot = ds_local + ds_next;
            dx = ds_tot * 0.15f;
            ds_prev = ds_tot * 0.85f;
            da_prev = 0.0f;
            dg = dy * dtanh * s_next;
            break;
        }
        case 6: { // SDSC_OP_AMPLIFY
            float dtanh = 1.0f - out * out;
            dx = dy * dtanh * g * 2.5f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = dy * dtanh * x * 2.5f;
            break;
        }
        case 7: { // SDSC_OP_INVERT
            float dtanh = 1.0f - out * out;
            dx = -dy * dtanh * g;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = -dy * dtanh * x;
            break;
        }
        case 8: { // SDSC_OP_DAMPER
            float ds_tot = dy + ds_next;
            dx = ds_tot * 0.30f;
            ds_prev = ds_tot * 0.70f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 9: { // SDSC_OP_CLIP
            float u = x * g;
            bool in_range = (u >= -1.0f && u <= 1.0f);
            dx = in_range ? (dy * g) : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = in_range ? (dy * x) : 0.0f;
            break;
        }
        case 10: { // SDSC_OP_ABS
            float tx = tanhf(x * g);
            float sgn = (tx > 0.0f) ? 1.0f : ((tx < 0.0f) ? -1.0f : 0.0f);
            float dtanh = 1.0f - tx * tx;
            dx = dy * sgn * dtanh * g;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = dy * sgn * dtanh * x;
            break;
        }
        case 11: { // SDSC_OP_MULTIPLY
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 12: { // SDSC_OP_DIFF
            dx = dy + ds_next;
            ds_prev = -dy;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 13: { // SDSC_OP_SUB
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 14: { // SDSC_OP_RATIO
            float denom = s_next + 0.1f;
            float u = x / denom;
            bool in_range = (u >= -2.0f && u <= 2.0f);
            float du = in_range ? dy : 0.0f;
            float sgn_x = (x > 0.0f) ? 1.0f : ((x < 0.0f) ? -1.0f : 0.0f);
            float ds_local = du * (-x / (denom * denom));
            float ds_tot = ds_local + ds_next;
            dx = du * (1.0f / denom) + ds_tot * 0.15f * sgn_x;
            ds_prev = ds_tot * 0.85f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 15: { // SDSC_OP_THRESHOLD
            dx = (fabsf(x) <= 1.0f) ? dy : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 16: { // SDSC_OP_HYSTERESIS
            dx = (fabsf(x) <= 1.0f) ? (dy * 0.5f) : 0.0f;
            ds_prev = ds_next * 0.90f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 17: { // SDSC_OP_DEADZONE
            dx = (fabsf(x) > fabsf(g)) ? dy : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 18: { // SDSC_OP_INHIBIT
            float tx = tanhf(x * g);
            float dtx = 1.0f - tx * tx;
            float gate = fmaxf(0.0f, 1.0f - s_next);
            float dgate = (1.0f - s_next > 0.0f) ? -1.0f : 0.0f;
            float ds_local = dy * tx * dgate;
            float ds_tot = ds_local + ds_next;
            float sgn_x = (x > 0.0f) ? 1.0f : ((x < 0.0f) ? -1.0f : 0.0f);
            dx = dy * gate * dtx * g + ds_tot * 0.20f * sgn_x;
            ds_prev = ds_tot * 0.80f;
            da_prev = 0.0f;
            dg = dy * gate * dtx * x;
            break;
        }
        case 19: { // SDSC_OP_AND
            dx = dy * 0.5f + ds_next;
            ds_prev = dy * 0.5f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 20: { // SDSC_OP_MIN_MAX
            dx = ((x >= s) ? dy : 0.0f) + ds_next;
            ds_prev = (x < s) ? dy : 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 21: { // SDSC_OP_ACT_POS
            float u = x * g;
            bool in_range = (u >= 0.0f && u <= 1.0f);
            dx = in_range ? (dy * g) : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = in_range ? (dy * x) : 0.0f;
            break;
        }
        case 22: { // SDSC_OP_ACT_NEG
            float u = -x * g;
            bool in_range = (u >= 0.0f && u <= 1.0f);
            dx = in_range ? (-dy * g) : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = in_range ? (-dy * x) : 0.0f;
            break;
        }
        case 23: { // SDSC_OP_ACT_RESET
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 24: { // SDSC_OP_CORRELATION
            float dtanh = 1.0f - out * out;
            float ds_local = dy * dtanh * g;
            float ds_tot = ds_local + ds_next;
            dx = ds_tot * (a * 0.10f) + da_next;
            da_prev = ds_tot * (x * 0.10f);
            ds_prev = ds_tot * 0.90f;
            dg = dy * dtanh * s_next;
            break;
        }
        case 25: { // SDSC_OP_FATIGUE
            float tx = tanhf(x * g);
            float dtx = 1.0f - tx * tx;
            float denom = 1.0f + s_next;
            float ds_local = -dy * tx / (denom * denom);
            float ds_tot = ds_local + ds_next;
            float s_raw = s + fabsf(x) * 0.15f;
            float dclamp = (s_raw < 2.0f) ? 0.96f : 0.0f;
            float sgn_x = (x > 0.0f) ? 1.0f : ((x < 0.0f) ? -1.0f : 0.0f);
            dx = dy * (dtx * g / denom) + ds_tot * dclamp * 0.15f * sgn_x;
            ds_prev = ds_tot * dclamp;
            da_prev = 0.0f;
            dg = dy * (dtx * x / denom);
            break;
        }
        case 26: { // SDSC_OP_PASSTHRU
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 27: { // SDSC_OP_ACCUMULATOR
            float active = (s_next > -16.0f && s_next < 16.0f) ? 1.0f : 0.0f;
            float dtot = dy + ds_next;
            dx = dtot * g * active;
            ds_prev = dtot * active;
            da_prev = 0.0f;
            dg = dtot * x * active;
            break;
        }
        default:
            dx = dy;
            break;
    }

    ret.dx = dx;
    ret.ds_prev = ds_prev;
    ret.da_prev = da_prev;
    ret.dg = dg;
    return ret;
}

// NVRTC JIT 反向伴随 VJP 动态内核代码模板字符串
static const char* const SDSC_CUDA_DEVICE_VJP_OPS_SRC = R"(
typedef struct {
    float dx;
    float ds_prev;
    float da_prev;
    float dg;
} SdscCUDAVJP;

SDSC_CUDA_DEVICE SdscCUDAVJP sdsc_cuda_vjp_primitive(
    uint8_t op,
    float g,
    float x,
    float s,
    float a,
    float out,
    float s_next,
    float a_next,
    float dy,
    float ds_next,
    float da_next
) {
    SdscCUDAVJP ret;
    float dx = 0.0f;
    float ds_prev = 0.0f;
    float da_prev = 0.0f;
    float dg = 0.0f;

    switch (op) {
        case 0: { // SDSC_OP_SENSE_0
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 1: { // SDSC_OP_SENSE_1
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 2: { // SDSC_OP_SENSE_2
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 3: { // SDSC_OP_SENSE_3
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 4: { // SDSC_OP_SUM
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 5: { // SDSC_OP_INTEGRATE
            float dtanh = 1.0f - out * out;
            float ds_local = dy * dtanh * g;
            float ds_tot = ds_local + ds_next;
            dx = ds_tot * 0.15f;
            ds_prev = ds_tot * 0.85f;
            da_prev = 0.0f;
            dg = dy * dtanh * s_next;
            break;
        }
        case 6: { // SDSC_OP_AMPLIFY
            float dtanh = 1.0f - out * out;
            dx = dy * dtanh * g * 2.5f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = dy * dtanh * x * 2.5f;
            break;
        }
        case 7: { // SDSC_OP_INVERT
            float dtanh = 1.0f - out * out;
            dx = -dy * dtanh * g;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = -dy * dtanh * x;
            break;
        }
        case 8: { // SDSC_OP_DAMPER
            float ds_tot = dy + ds_next;
            dx = ds_tot * 0.30f;
            ds_prev = ds_tot * 0.70f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 9: { // SDSC_OP_CLIP
            float u = x * g;
            bool in_range = (u >= -1.0f && u <= 1.0f);
            dx = in_range ? (dy * g) : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = in_range ? (dy * x) : 0.0f;
            break;
        }
        case 10: { // SDSC_OP_ABS
            float tx = tanhf(x * g);
            float sgn = (tx > 0.0f) ? 1.0f : ((tx < 0.0f) ? -1.0f : 0.0f);
            float dtanh = 1.0f - tx * tx;
            dx = dy * sgn * dtanh * g;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = dy * sgn * dtanh * x;
            break;
        }
        case 11: { // SDSC_OP_MULTIPLY
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 12: { // SDSC_OP_DIFF
            dx = dy + ds_next;
            ds_prev = -dy;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 13: { // SDSC_OP_SUB
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 14: { // SDSC_OP_RATIO
            float denom = s_next + 0.1f;
            float u = x / denom;
            bool in_range = (u >= -2.0f && u <= 2.0f);
            float du = in_range ? dy : 0.0f;
            float sgn_x = (x > 0.0f) ? 1.0f : ((x < 0.0f) ? -1.0f : 0.0f);
            float ds_local = du * (-x / (denom * denom));
            float ds_tot = ds_local + ds_next;
            dx = du * (1.0f / denom) + ds_tot * 0.15f * sgn_x;
            ds_prev = ds_tot * 0.85f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 15: { // SDSC_OP_THRESHOLD
            dx = (fabsf(x) <= 1.0f) ? dy : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 16: { // SDSC_OP_HYSTERESIS
            dx = (fabsf(x) <= 1.0f) ? (dy * 0.5f) : 0.0f;
            ds_prev = ds_next * 0.90f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 17: { // SDSC_OP_DEADZONE
            dx = (fabsf(x) > fabsf(g)) ? dy : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 18: { // SDSC_OP_INHIBIT
            float tx = tanhf(x * g);
            float dtx = 1.0f - tx * tx;
            float gate = fmaxf(0.0f, 1.0f - s_next);
            float dgate = (1.0f - s_next > 0.0f) ? -1.0f : 0.0f;
            float ds_local = dy * tx * dgate;
            float ds_tot = ds_local + ds_next;
            float sgn_x = (x > 0.0f) ? 1.0f : ((x < 0.0f) ? -1.0f : 0.0f);
            dx = dy * gate * dtx * g + ds_tot * 0.20f * sgn_x;
            ds_prev = ds_tot * 0.80f;
            da_prev = 0.0f;
            dg = dy * gate * dtx * x;
            break;
        }
        case 19: { // SDSC_OP_AND
            dx = dy * 0.5f + ds_next;
            ds_prev = dy * 0.5f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 20: { // SDSC_OP_MIN_MAX
            dx = ((x >= s) ? dy : 0.0f) + ds_next;
            ds_prev = (x < s) ? dy : 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 21: { // SDSC_OP_ACT_POS
            float u = x * g;
            bool in_range = (u >= 0.0f && u <= 1.0f);
            dx = in_range ? (dy * g) : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = in_range ? (dy * x) : 0.0f;
            break;
        }
        case 22: { // SDSC_OP_ACT_NEG
            float u = -x * g;
            bool in_range = (u >= 0.0f && u <= 1.0f);
            dx = in_range ? (-dy * g) : 0.0f;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = in_range ? (-dy * x) : 0.0f;
            break;
        }
        case 23: { // SDSC_OP_ACT_RESET
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 24: { // SDSC_OP_CORRELATION
            float dtanh = 1.0f - out * out;
            float ds_local = dy * dtanh * g;
            float ds_tot = ds_local + ds_next;
            dx = ds_tot * (a * 0.10f) + da_next;
            da_prev = ds_tot * (x * 0.10f);
            ds_prev = ds_tot * 0.90f;
            dg = dy * dtanh * s_next;
            break;
        }
        case 25: { // SDSC_OP_FATIGUE
            float tx = tanhf(x * g);
            float dtx = 1.0f - tx * tx;
            float denom = 1.0f + s_next;
            float ds_local = -dy * tx / (denom * denom);
            float ds_tot = ds_local + ds_next;
            float s_raw = s + fabsf(x) * 0.15f;
            float dclamp = (s_raw < 2.0f) ? 0.96f : 0.0f;
            float sgn_x = (x > 0.0f) ? 1.0f : ((x < 0.0f) ? -1.0f : 0.0f);
            dx = dy * (dtx * g / denom) + ds_tot * dclamp * 0.15f * sgn_x;
            ds_prev = ds_tot * dclamp;
            da_prev = 0.0f;
            dg = dy * (dtx * x / denom);
            break;
        }
        case 26: { // SDSC_OP_PASSTHRU
            dx = dy;
            ds_prev = 0.0f;
            da_prev = 0.0f;
            dg = 0.0f;
            break;
        }
        case 27: { // SDSC_OP_ACCUMULATOR
            float active = (s_next > -16.0f && s_next < 16.0f) ? 1.0f : 0.0f;
            float dtot = dy + ds_next;
            dx = dtot * g * active;
            ds_prev = dtot * active;
            da_prev = 0.0f;
            dg = dtot * x * active;
            break;
        }
        default:
            dx = dy;
            break;
    }

    ret.dx = dx;
    ret.ds_prev = ds_prev;
    ret.da_prev = da_prev;
    ret.dg = dg;
    return ret;
}
)";

#endif /* KUN_CELLULAR_CUDA_OPS_VJP_CUH_ */
