/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */

#ifndef KUN_CELLULAR_CUDA_OPS_CUH_
#define KUN_CELLULAR_CUDA_OPS_CUH_

#include <stdint.h>
#include <math.h>

#if defined(__CUDACC__) || defined(__CUDA_ARCH__)
#define SDSC_CUDA_DEVICE __device__ __forceinline__
#else
#define SDSC_CUDA_DEVICE inline
#endif

SDSC_CUDA_DEVICE float sdsc_cuda_eval_primitive(
    uint8_t op,
    float gain,
    float x,
    float* state,
    float* aux
) {
    float out = 0.0f;
    float s = *state;
    float a = *aux;
    float g = gain;

    switch (op) {
        case 0: { // SDSC_OP_SENSE_0
            out = x;
            break;
        }
        case 1: { // SDSC_OP_SENSE_1
            out = x;
            break;
        }
        case 2: { // SDSC_OP_SENSE_2
            out = x;
            break;
        }
        case 3: { // SDSC_OP_SENSE_3
            out = x;
            break;
        }
        case 4: { // SDSC_OP_SUM
            out = x;
            break;
        }
        case 5: { // SDSC_OP_INTEGRATE
            float next_s = s * 0.85f + x * 0.15f;
            s = next_s;
            float drive = s * g;
            out = tanhf(drive);
            break;
        }
        case 6: { // SDSC_OP_AMPLIFY
            float drive = x * g * 2.5f;
            out = tanhf(drive);
            break;
        }
        case 7: { // SDSC_OP_INVERT
            float drive = x * g;
            out = -tanhf(drive);
            break;
        }
        case 8: { // SDSC_OP_DAMPER
            s = s * 0.70f + x * 0.30f;
            out = s;
            break;
        }
        case 9: { // SDSC_OP_CLIP
            float drive = x * g;
            out = fminf(fmaxf(drive, -1.0f), 1.0f);
            break;
        }
        case 10: { // SDSC_OP_ABS
            float drive = x * g;
            out = fabsf(tanhf(drive));
            break;
        }
        case 11: { // SDSC_OP_MULTIPLY
            out = x;
            break;
        }
        case 12: { // SDSC_OP_DIFF
            float difference = x - s;
            out = difference;
            s = x;
            break;
        }
        case 13: { // SDSC_OP_SUB
            out = x;
            break;
        }
        case 14: { // SDSC_OP_RATIO
            float next_s = s * 0.85f + fabsf(x) * 0.15f;
            s = next_s;
            float denominator = s + 0.1f;
            float ratio = x / denominator;
            out = fminf(fmaxf(ratio, -2.0f), 2.0f);
            break;
        }
        case 15: { // SDSC_OP_THRESHOLD
            out = (x > g) ? 1.0f : 0.0f;
            break;
        }
        case 16: { // SDSC_OP_HYSTERESIS
            if (x > g) s = 1.0f;
            else if (x < -g) s = -1.0f;
            out = s;
            break;
        }
        case 17: { // SDSC_OP_DEADZONE
            out = (fabsf(x) > fabsf(g)) ? x : 0.0f;
            break;
        }
        case 18: { // SDSC_OP_INHIBIT
            float next_s = s * 0.80f + fabsf(x) * 0.20f;
            s = next_s;
            float drive = x * g;
            float remaining = fmaxf(0.0f, 1.0f - s);
            float gated = tanhf(drive) * remaining;
            out = gated;
            break;
        }
        case 19: { // SDSC_OP_AND
            out = (x > 0.0f && s > 0.0f) ? 1.0f : 0.0f;
            s = x;
            break;
        }
        case 20: { // SDSC_OP_MIN_MAX
            out = fmaxf(x, s);
            s = x;
            break;
        }
        case 21: { // SDSC_OP_ACT_POS
            float drive = x * g;
            out = fminf(fmaxf(drive, 0.0f), 1.0f);
            break;
        }
        case 22: { // SDSC_OP_ACT_NEG
            float drive = -x * g;
            out = fminf(fmaxf(drive, 0.0f), 1.0f);
            break;
        }
        case 23: { // SDSC_OP_ACT_RESET
            out = (fabsf(x) < 0.10f) ? 0.0f : x;
            break;
        }
        case 24: { // SDSC_OP_CORRELATION
            float product = x * a;
            float next_s = s * 0.90f + product * 0.10f;
            s = next_s;
            a = x;
            float drive = s * g;
            out = tanhf(drive);
            break;
        }
        case 25: { // SDSC_OP_FATIGUE
            float raw = s + fabsf(x) * 0.15f;
            float capped = fminf(2.0f, raw);
            s = capped * 0.96f;
            float drive = x * g;
            float denominator = 1.0f + s;
            float response = tanhf(drive) / denominator;
            out = response;
            break;
        }
        case 26: { // SDSC_OP_PASSTHRU
            out = x;
            break;
        }
        case 27: { // SDSC_OP_ACCUMULATOR
            float increment = x * g;
            float next_s = s + increment;
            s = fminf(fmaxf(next_s, -16.0f), 16.0f);
            out = s;
            break;
        }
        default:
            out = x;
            break;
    }

    *state = s;
    *aux   = a;
    return out;
}

// NVRTC JIT 动态内核代码注入模板字符串 (消除手写 CUDA JIT 源码漂移)
static const char* const SDSC_CUDA_DEVICE_OPS_SRC = R"(
__device__ __forceinline__ float sdsc_cuda_eval_primitive(
    uint8_t op,
    float gain,
    float x,
    float* state,
    float* aux
) {
    float out = 0.0f;
    float s = *state;
    float a = *aux;
    float g = gain;

    switch (op) {
        case 0: { // SDSC_OP_SENSE_0
            out = x;
            break;
        }
        case 1: { // SDSC_OP_SENSE_1
            out = x;
            break;
        }
        case 2: { // SDSC_OP_SENSE_2
            out = x;
            break;
        }
        case 3: { // SDSC_OP_SENSE_3
            out = x;
            break;
        }
        case 4: { // SDSC_OP_SUM
            out = x;
            break;
        }
        case 5: { // SDSC_OP_INTEGRATE
            float next_s = s * 0.85f + x * 0.15f;
            s = next_s;
            float drive = s * g;
            out = tanhf(drive);
            break;
        }
        case 6: { // SDSC_OP_AMPLIFY
            float drive = x * g * 2.5f;
            out = tanhf(drive);
            break;
        }
        case 7: { // SDSC_OP_INVERT
            float drive = x * g;
            out = -tanhf(drive);
            break;
        }
        case 8: { // SDSC_OP_DAMPER
            s = s * 0.70f + x * 0.30f;
            out = s;
            break;
        }
        case 9: { // SDSC_OP_CLIP
            float drive = x * g;
            out = fminf(fmaxf(drive, -1.0f), 1.0f);
            break;
        }
        case 10: { // SDSC_OP_ABS
            float drive = x * g;
            out = fabsf(tanhf(drive));
            break;
        }
        case 11: { // SDSC_OP_MULTIPLY
            out = x;
            break;
        }
        case 12: { // SDSC_OP_DIFF
            float difference = x - s;
            out = difference;
            s = x;
            break;
        }
        case 13: { // SDSC_OP_SUB
            out = x;
            break;
        }
        case 14: { // SDSC_OP_RATIO
            float next_s = s * 0.85f + fabsf(x) * 0.15f;
            s = next_s;
            float denominator = s + 0.1f;
            float ratio = x / denominator;
            out = fminf(fmaxf(ratio, -2.0f), 2.0f);
            break;
        }
        case 15: { // SDSC_OP_THRESHOLD
            out = (x > g) ? 1.0f : 0.0f;
            break;
        }
        case 16: { // SDSC_OP_HYSTERESIS
            if (x > g) s = 1.0f;
            else if (x < -g) s = -1.0f;
            out = s;
            break;
        }
        case 17: { // SDSC_OP_DEADZONE
            out = (fabsf(x) > fabsf(g)) ? x : 0.0f;
            break;
        }
        case 18: { // SDSC_OP_INHIBIT
            float next_s = s * 0.80f + fabsf(x) * 0.20f;
            s = next_s;
            float drive = x * g;
            float remaining = fmaxf(0.0f, 1.0f - s);
            float gated = tanhf(drive) * remaining;
            out = gated;
            break;
        }
        case 19: { // SDSC_OP_AND
            out = (x > 0.0f && s > 0.0f) ? 1.0f : 0.0f;
            s = x;
            break;
        }
        case 20: { // SDSC_OP_MIN_MAX
            out = fmaxf(x, s);
            s = x;
            break;
        }
        case 21: { // SDSC_OP_ACT_POS
            float drive = x * g;
            out = fminf(fmaxf(drive, 0.0f), 1.0f);
            break;
        }
        case 22: { // SDSC_OP_ACT_NEG
            float drive = -x * g;
            out = fminf(fmaxf(drive, 0.0f), 1.0f);
            break;
        }
        case 23: { // SDSC_OP_ACT_RESET
            out = (fabsf(x) < 0.10f) ? 0.0f : x;
            break;
        }
        case 24: { // SDSC_OP_CORRELATION
            float product = x * a;
            float next_s = s * 0.90f + product * 0.10f;
            s = next_s;
            a = x;
            float drive = s * g;
            out = tanhf(drive);
            break;
        }
        case 25: { // SDSC_OP_FATIGUE
            float raw = s + fabsf(x) * 0.15f;
            float capped = fminf(2.0f, raw);
            s = capped * 0.96f;
            float drive = x * g;
            float denominator = 1.0f + s;
            float response = tanhf(drive) / denominator;
            out = response;
            break;
        }
        case 26: { // SDSC_OP_PASSTHRU
            out = x;
            break;
        }
        case 27: { // SDSC_OP_ACCUMULATOR
            float increment = x * g;
            float next_s = s + increment;
            s = fminf(fmaxf(next_s, -16.0f), 16.0f);
            out = s;
            break;
        }
        default:
            out = x;
            break;
    }

    *state = s;
    *aux   = a;
    return out;
}
)";

#include "cuda_ops_vjp.cuh"

#endif /* KUN_CELLULAR_CUDA_OPS_CUH_ */
