/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */

#ifndef KUN_CELLULAR_SDSC_CELL_KERNEL_H_
#define KUN_CELLULAR_SDSC_CELL_KERNEL_H_

#include <stdbool.h>
#include <float.h>
#include <stddef.h>
#include <stdint.h>
#include <limits.h>
#include <math.h>
#include "kun/cellular/sdsc_primitives.h"

#if (defined(__GNUC__) || defined(__clang__)) && !defined(__STRICT_ANSI__)
#define SDSC_CELL_KERNEL_INLINE static inline __attribute__((always_inline))
#else
#define SDSC_CELL_KERNEL_INLINE static inline
#endif

typedef enum {
    SDSC_CELL_SENSE_RAW_INPUT_0 = 0,
    SDSC_CELL_SENSE_RAW_INPUT_1 = 1,
    SDSC_CELL_SENSE_RAW_INPUT_2 = 2,
    SDSC_CELL_SENSE_RAW_INPUT_3 = 3,
    SDSC_CELL_SENSE_CHANNEL = 4,
    SDSC_CELL_OP_EMA = 10,
    SDSC_CELL_OP_DIFF = 11,
    SDSC_CELL_OP_INTEGRAL = 12,
    SDSC_CELL_OP_SUM = 13,
    SDSC_CELL_OP_SUB = 14,
    SDSC_CELL_OP_MULTIPLY = 15,
    SDSC_CELL_OP_RATIO = 16,
    SDSC_CELL_OP_ABS = 17,
    SDSC_CELL_OP_DELAY_N = 18,
    SDSC_CELL_OP_OSCILLATOR = 19,
    SDSC_CELL_OP_QUADRATIC = 20,
    SDSC_CELL_GATE_THRESHOLD = 24,
    SDSC_CELL_GATE_HYSTERESIS = 25,
    SDSC_CELL_GATE_AND = 26,
    SDSC_CELL_GATE_INHIBIT = 27,
    SDSC_CELL_GATE_DEADZONE = 28,
    SDSC_CELL_GATE_MIN_MAX = 29,
    SDSC_CELL_ACT_PRIMARY_POSITIVE = 30,
    SDSC_CELL_ACT_PRIMARY_NEGATIVE = 31,
    SDSC_CELL_ACT_DEFENSIVE_RESET = 32,
    SDSC_CELL_ACT_IMMUNE_BLOCK = 33,
    SDSC_CELL_ACT_CHANNEL = 34,
    SDSC_CELL_PREDICT_SENSE_0 = 40,
    SDSC_CELL_PREDICT_SENSE_1 = 41,
    SDSC_CELL_ASSOCIATION_HUB = 42
} SdscCellTypeCode;

typedef enum {
    SDSC_CELL_KERNEL_OK = 0,
    SDSC_CELL_KERNEL_INVALID_ARGUMENT = 1,
    SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE = 2,
    SDSC_CELL_KERNEL_INVALID_PARAMETER = 3,
    SDSC_CELL_KERNEL_INVALID_PROFILE = 4,
    SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND = 5,
    SDSC_CELL_KERNEL_NONFINITE = 6,
    SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE = 7,
    SDSC_CELL_KERNEL_INVALID_STATE = 8,
    SDSC_CELL_KERNEL_NUMERICAL_ERROR = 9,
} SdscCellKernelStatus;

typedef enum {
    SDSC_CELL_KERNEL_PROFILE_LEGACY_COMPATIBLE = 0,
    SDSC_CELL_KERNEL_PROFILE_STRICT_CORE = 1,
} SdscCellKernelProfile;

typedef enum {
    SDSC_CELL_PARAMETER_CONTINUOUS = 0,
    SDSC_CELL_PARAMETER_CHANNEL_INDEX = 1,
    SDSC_CELL_PARAMETER_DELAY_TICKS = 2,
    SDSC_CELL_PARAMETER_MIN_MAX_MODE = 3,
    SDSC_CELL_PARAMETER_UNUSED = 4,
} SdscCellKernelParameterKind;

typedef struct {
    SdscCellKernelParameterKind kind;
    union {
        double continuous;
        size_t channel_index;
        uint64_t delay_ticks;
        uint8_t min_max_mode;
    } value;
} SdscCellKernelStrictParameter;

typedef struct {
    SdscCellKernelStrictParameter param1;
    SdscCellKernelStrictParameter param2;
} SdscCellKernelStrictParameters;

SDSC_CELL_KERNEL_INLINE const char* sdsc_cell_kernel_status_string(
    SdscCellKernelStatus status) {
    switch (status) {
        case SDSC_CELL_KERNEL_OK: return "ok";
        case SDSC_CELL_KERNEL_INVALID_ARGUMENT: return "invalid argument";
        case SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE: return "unknown cell type";
        case SDSC_CELL_KERNEL_INVALID_PARAMETER: return "invalid parameter";
        case SDSC_CELL_KERNEL_INVALID_PROFILE: return "invalid profile";
        case SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND: return "invalid parameter kind";
        case SDSC_CELL_KERNEL_NONFINITE: return "non-finite value";
        case SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE: return "input out of range";
        case SDSC_CELL_KERNEL_INVALID_STATE: return "invalid state";
        case SDSC_CELL_KERNEL_NUMERICAL_ERROR: return "numerical error";
        default: return "unknown kernel status";
    }
}

typedef struct {
    double* state_val;
    double* aux_state;
    double* prev_input;
    double* output_val;
    double* delay_buffer;
    bool* latch_state;
    uint8_t* delay_idx;
    uint32_t activation_count;
} SdscCellKernelStateView;

/* Strict cell-kernel policy: finite consumed values, checked double-to-float
 * narrowing, checked intermediates before equation clamps, and finite
 * published state/output are required. Schema-defined clamps remain part
 * of the equation. activity_count is optional and is never read or changed
 * by strict execution; graph input-tensor validation is a later layer. */
typedef struct {
    double* state_val;
    double* aux_state;
    double* prev_input;
    double* output_val;
    double* delay_buffer;
    bool* latch_state;
    uint8_t* delay_idx;
    bool* initialized;
    const uint32_t* activity_count;
} SdscCellKernelStrictStateView;

typedef struct {
    float state_min;
    float state_max;
    float out_min;
    float out_max;
} SdscCellKernelBounds;

typedef struct {
    double param1;
    double param2;
    size_t channel;
    int delay_ticks;
} SdscCellKernelNormalizedParameters;

SDSC_CELL_KERNEL_INLINE bool sdsc_cell_type_is_valid(uint8_t cell_type) {
    switch (cell_type) {
        case SDSC_CELL_SENSE_RAW_INPUT_0:
        case SDSC_CELL_SENSE_RAW_INPUT_1:
        case SDSC_CELL_SENSE_RAW_INPUT_2:
        case SDSC_CELL_SENSE_RAW_INPUT_3:
        case SDSC_CELL_SENSE_CHANNEL:
        case SDSC_CELL_OP_EMA:
        case SDSC_CELL_OP_DIFF:
        case SDSC_CELL_OP_INTEGRAL:
        case SDSC_CELL_OP_SUM:
        case SDSC_CELL_OP_SUB:
        case SDSC_CELL_OP_MULTIPLY:
        case SDSC_CELL_OP_RATIO:
        case SDSC_CELL_OP_ABS:
        case SDSC_CELL_OP_DELAY_N:
        case SDSC_CELL_OP_OSCILLATOR:
        case SDSC_CELL_OP_QUADRATIC:
        case SDSC_CELL_GATE_THRESHOLD:
        case SDSC_CELL_GATE_HYSTERESIS:
        case SDSC_CELL_GATE_AND:
        case SDSC_CELL_GATE_INHIBIT:
        case SDSC_CELL_GATE_DEADZONE:
        case SDSC_CELL_GATE_MIN_MAX:
        case SDSC_CELL_ACT_PRIMARY_POSITIVE:
        case SDSC_CELL_ACT_PRIMARY_NEGATIVE:
        case SDSC_CELL_ACT_DEFENSIVE_RESET:
        case SDSC_CELL_ACT_IMMUNE_BLOCK:
        case SDSC_CELL_ACT_CHANNEL:
        case SDSC_CELL_PREDICT_SENSE_0:
        case SDSC_CELL_PREDICT_SENSE_1:
        case SDSC_CELL_ASSOCIATION_HUB:
            return true;
        default:
            return false;
    }
}

SDSC_CELL_KERNEL_INLINE uint8_t sdsc_cell_type_to_legacy_eval_op(uint8_t cell_type) {
    switch (cell_type) {
        case SDSC_CELL_SENSE_RAW_INPUT_0: return 0;
        case SDSC_CELL_SENSE_RAW_INPUT_1: return 1;
        case SDSC_CELL_SENSE_RAW_INPUT_2: return 2;
        case SDSC_CELL_SENSE_RAW_INPUT_3: return 3;
        case SDSC_CELL_SENSE_CHANNEL: return 0;
        case SDSC_CELL_OP_EMA: return 8;
        case SDSC_CELL_OP_DIFF: return 12;
        case SDSC_CELL_OP_INTEGRAL: return 27;
        case SDSC_CELL_OP_SUM: return 4;
        case SDSC_CELL_OP_SUB: return 13;
        case SDSC_CELL_OP_MULTIPLY: return 11;
        case SDSC_CELL_OP_RATIO: return 14;
        case SDSC_CELL_OP_ABS: return 10;
        case SDSC_CELL_OP_DELAY_N: return 26;
        case SDSC_CELL_OP_OSCILLATOR: return 26;
        case SDSC_CELL_OP_QUADRATIC: return 26;
        case SDSC_CELL_GATE_THRESHOLD: return 15;
        case SDSC_CELL_GATE_HYSTERESIS: return 16;
        case SDSC_CELL_GATE_AND: return 19;
        case SDSC_CELL_GATE_INHIBIT: return 18;
        case SDSC_CELL_GATE_DEADZONE: return 17;
        case SDSC_CELL_GATE_MIN_MAX: return 20;
        case SDSC_CELL_ACT_PRIMARY_POSITIVE: return 21;
        case SDSC_CELL_ACT_PRIMARY_NEGATIVE: return 22;
        case SDSC_CELL_ACT_DEFENSIVE_RESET: return 23;
        case SDSC_CELL_ACT_IMMUNE_BLOCK: return 23;
        case SDSC_CELL_ACT_CHANNEL: return 26;
        case SDSC_CELL_PREDICT_SENSE_0: return 26;
        case SDSC_CELL_PREDICT_SENSE_1: return 26;
        case SDSC_CELL_ASSOCIATION_HUB: return 24;
        default: return 26;
    }
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelBounds sdsc_cell_kernel_bounds(uint8_t op) {
    switch (op) {
        case 0: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 1: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 2: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 3: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 4: {
            SdscCellKernelBounds result = {0.0f, 0.0f, -16.0f, 16.0f};
            return result;
        }
        case 5: {
            SdscCellKernelBounds result = {-4.0f, 4.0f, -1.0f, 1.0f};
            return result;
        }
        case 6: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1.0f, 1.0f};
            return result;
        }
        case 7: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1.0f, 1.0f};
            return result;
        }
        case 8: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 9: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1.0f, 1.0f};
            return result;
        }
        case 10: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, 0.0f, 1.0f};
            return result;
        }
        case 11: {
            SdscCellKernelBounds result = {0.0f, 0.0f, -16.0f, 16.0f};
            return result;
        }
        case 12: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 13: {
            SdscCellKernelBounds result = {0.0f, 0.0f, -16.0f, 16.0f};
            return result;
        }
        case 14: {
            SdscCellKernelBounds result = {0.0f, 1000000000.0f, -2.0f, 2.0f};
            return result;
        }
        case 15: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1.0f, 1.0f};
            return result;
        }
        case 16: {
            SdscCellKernelBounds result = {-1.0f, 1.0f, -1.0f, 1.0f};
            return result;
        }
        case 17: {
            SdscCellKernelBounds result = {0.0f, 0.0f, -16.0f, 16.0f};
            return result;
        }
        case 18: {
            SdscCellKernelBounds result = {0.0f, 1000000000.0f, -1.0f, 1.0f};
            return result;
        }
        case 19: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, 0.0f, 1.0f};
            return result;
        }
        case 20: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 21: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, 0.0f, 1.0f};
            return result;
        }
        case 22: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, 0.0f, 1.0f};
            return result;
        }
        case 23: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 24: {
            SdscCellKernelBounds result = {-1.0f, 1.0f, -1.0f, 1.0f};
            return result;
        }
        case 25: {
            SdscCellKernelBounds result = {0.0f, 2.0f, -1.0f, 1.0f};
            return result;
        }
        case 26: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f, -1000000000.0f, 1000000000.0f};
            return result;
        }
        case 27: {
            SdscCellKernelBounds result = {-16.0f, 16.0f, -16.0f, 16.0f};
            return result;
        }
        default: {
            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f,
                -1000000000.0f, 1000000000.0f};
            return result;
        }
    }
}

SDSC_CELL_KERNEL_INLINE double sdsc_cell_kernel_clamp_double(
    double value, double lower, double upper) {
    return value < lower ? lower : (value > upper ? upper : value);
}

SDSC_CELL_KERNEL_INLINE float sdsc_cell_kernel_clamp_float(
    float value, float lower, float upper) {
    return value < lower ? lower : (value > upper ? upper : value);
}

SDSC_CELL_KERNEL_INLINE bool sdsc_cell_kernel_normalize_delay(
    double param1, int* delay_ticks) {
    if (delay_ticks == NULL) return false;
    const double scaled_delay = param1 * 16.0;
    const double floored_delay = floor(scaled_delay);
    if (!isfinite(scaled_delay) || floored_delay < (double)INT_MIN ||
        floored_delay > (double)INT_MAX) {
        return false;
    }
    int normalized = (int)floored_delay;
    if (normalized < 1) normalized = 1;
    if (normalized > 16) normalized = 16;
    *delay_ticks = normalized;
    return true;
}

SDSC_CELL_KERNEL_INLINE bool sdsc_cell_kernel_strict_double_to_float(
    double value, float* narrowed) {
    if (narrowed == NULL || !isfinite(value) ||
        value < -(double)FLT_MAX || value > (double)FLT_MAX)
        return false;
    *narrowed = (float)value;
    return isfinite(*narrowed);
}

SDSC_CELL_KERNEL_INLINE bool sdsc_cell_kernel_strict_finite_state(
    const SdscCellKernelStateView* state) {
    if (!isfinite(*state->state_val) || !isfinite(*state->aux_state) ||
        !isfinite(*state->prev_input) || !isfinite(*state->output_val) ||
        *state->delay_idx >= 16u) return false;
    for (size_t i = 0; i < 16u; ++i) {
        if (!isfinite(state->delay_buffer[i])) return false;
    }
    return true;
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus
sdsc_cell_kernel_strict_parameter_kinds(
    uint8_t cell_type, const SdscCellKernelStrictParameters* parameters) {
    if (parameters == NULL) return SDSC_CELL_KERNEL_INVALID_ARGUMENT;
    switch (cell_type) {
        case SDSC_CELL_SENSE_RAW_INPUT_0:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_SENSE_RAW_INPUT_1:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_SENSE_RAW_INPUT_2:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_SENSE_RAW_INPUT_3:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_SENSE_CHANNEL:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_CHANNEL_INDEX
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_EMA:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_DIFF:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_INTEGRAL:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_SUM:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_SUB:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_MULTIPLY:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_RATIO:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_ABS:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_DELAY_N:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_DELAY_TICKS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_OSCILLATOR:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_CONTINUOUS
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_OP_QUADRATIC:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_CONTINUOUS
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_GATE_THRESHOLD:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_GATE_HYSTERESIS:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_CONTINUOUS
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_GATE_AND:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_GATE_INHIBIT:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_GATE_DEADZONE:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_GATE_MIN_MAX:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_MIN_MAX_MODE
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_ACT_PRIMARY_POSITIVE:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_ACT_PRIMARY_NEGATIVE:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_ACT_DEFENSIVE_RESET:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_ACT_IMMUNE_BLOCK:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_ACT_CHANNEL:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_CHANNEL_INDEX
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_PREDICT_SENSE_0:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_PREDICT_SENSE_1:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_UNUSED
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        case SDSC_CELL_ASSOCIATION_HUB:
            if (
                parameters->param1.kind != SDSC_CELL_PARAMETER_CONTINUOUS
 || parameters->param2.kind != SDSC_CELL_PARAMETER_UNUSED
            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;
            break;
        default:
            return SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;
    }
    return SDSC_CELL_KERNEL_OK;
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus
sdsc_cell_kernel_normalize_strict_parameters(
    uint8_t cell_type, const SdscCellKernelStrictParameters* parameters,
    SdscCellKernelNormalizedParameters* normalized) {
    if (parameters == NULL || normalized == NULL) return SDSC_CELL_KERNEL_INVALID_ARGUMENT;
    normalized->param1 = 1.0;
    normalized->param2 = 0.0;
    normalized->channel = 0u;
    normalized->delay_ticks = 0;
    const SdscCellKernelStatus kind_status =
        sdsc_cell_kernel_strict_parameter_kinds(cell_type, parameters);
    if (kind_status != SDSC_CELL_KERNEL_OK) return kind_status;
    switch (cell_type) {
        case SDSC_CELL_SENSE_RAW_INPUT_0: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_SENSE_RAW_INPUT_1: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_SENSE_RAW_INPUT_2: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_SENSE_RAW_INPUT_3: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_SENSE_CHANNEL: {
            normalized->param1 = parameters->param1.value.continuous;
            normalized->channel = parameters->param2.value.channel_index;
            break;
        }
        case SDSC_CELL_OP_EMA: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_OP_DIFF: {
            break;
        }
        case SDSC_CELL_OP_INTEGRAL: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_OP_SUM: {
            break;
        }
        case SDSC_CELL_OP_SUB: {
            break;
        }
        case SDSC_CELL_OP_MULTIPLY: {
            break;
        }
        case SDSC_CELL_OP_RATIO: {
            break;
        }
        case SDSC_CELL_OP_ABS: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_OP_DELAY_N: {
            if (parameters->param1.value.delay_ticks < 1u ||
                parameters->param1.value.delay_ticks > 16u)
                return SDSC_CELL_KERNEL_INVALID_PARAMETER;
            normalized->delay_ticks = (int)parameters->param1.value.delay_ticks;
            break;
        }
        case SDSC_CELL_OP_OSCILLATOR: {
            normalized->param1 = parameters->param1.value.continuous;
            normalized->param2 = parameters->param2.value.continuous;
            break;
        }
        case SDSC_CELL_OP_QUADRATIC: {
            normalized->param1 = parameters->param1.value.continuous;
            normalized->param2 = parameters->param2.value.continuous;
            break;
        }
        case SDSC_CELL_GATE_THRESHOLD: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_GATE_HYSTERESIS: {
            normalized->param1 = parameters->param1.value.continuous;
            normalized->param2 = parameters->param2.value.continuous;
            break;
        }
        case SDSC_CELL_GATE_AND: {
            break;
        }
        case SDSC_CELL_GATE_INHIBIT: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_GATE_DEADZONE: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        case SDSC_CELL_GATE_MIN_MAX: {
            if (parameters->param1.value.min_max_mode > 1u)
                return SDSC_CELL_KERNEL_INVALID_PARAMETER;
            normalized->param1 = parameters->param1.value.min_max_mode ? 1.0 : 0.0;
            break;
        }
        case SDSC_CELL_ACT_PRIMARY_POSITIVE: {
            break;
        }
        case SDSC_CELL_ACT_PRIMARY_NEGATIVE: {
            break;
        }
        case SDSC_CELL_ACT_DEFENSIVE_RESET: {
            break;
        }
        case SDSC_CELL_ACT_IMMUNE_BLOCK: {
            break;
        }
        case SDSC_CELL_ACT_CHANNEL: {
            normalized->channel = parameters->param2.value.channel_index;
            break;
        }
        case SDSC_CELL_PREDICT_SENSE_0: {
            break;
        }
        case SDSC_CELL_PREDICT_SENSE_1: {
            break;
        }
        case SDSC_CELL_ASSOCIATION_HUB: {
            normalized->param1 = parameters->param1.value.continuous;
            break;
        }
        default:
            return SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;
    }
    if (!isfinite(normalized->param1) || !isfinite(normalized->param2))
        return SDSC_CELL_KERNEL_INVALID_PARAMETER;
    return SDSC_CELL_KERNEL_OK;
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step_common(
    uint8_t cell_type, const SdscCellKernelNormalizedParameters* parameters,
    double in0, double in1, size_t in_dim, const double* inputs,
    SdscCellKernelStateView* state, bool strict, bool* initialized) {
    double next_state = *state->state_val;
    double next_aux = *state->aux_state;
    double next_previous = *state->prev_input;
    double next_output = *state->output_val;
    double next_delay[16];
    for (size_t i = 0; i < 16u; ++i) next_delay[i] = state->delay_buffer[i];
    bool next_latch = *state->latch_state;
    uint8_t next_delay_index = *state->delay_idx;
    if (strict) {
        if (initialized == NULL || !sdsc_cell_kernel_strict_finite_state(state))
            return initialized == NULL ? SDSC_CELL_KERNEL_INVALID_ARGUMENT :
                SDSC_CELL_KERNEL_INVALID_STATE;
        if (cell_type != SDSC_CELL_SENSE_RAW_INPUT_0 &&
            cell_type != SDSC_CELL_SENSE_RAW_INPUT_1 &&
            cell_type != SDSC_CELL_SENSE_RAW_INPUT_2 &&
            cell_type != SDSC_CELL_SENSE_RAW_INPUT_3 &&
            cell_type != SDSC_CELL_SENSE_CHANNEL && !isfinite(in0))
            return SDSC_CELL_KERNEL_NONFINITE;
        if ((cell_type == SDSC_CELL_OP_SUM || cell_type == SDSC_CELL_OP_SUB ||
             cell_type == SDSC_CELL_OP_MULTIPLY || cell_type == SDSC_CELL_OP_QUADRATIC ||
             cell_type == SDSC_CELL_GATE_MIN_MAX) && !isfinite(in1))
            return SDSC_CELL_KERNEL_NONFINITE;
    }

    if (cell_type == SDSC_CELL_SENSE_RAW_INPUT_0) {
        if (strict && (inputs == NULL || in_dim <= 0))
            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;
        if (!strict) {
            next_output = (in_dim > 0 && inputs) ?
                inputs[0] * parameters->param1 : 0.0;
        } else {
            const double source = inputs[0];
            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;
            next_output = source * parameters->param1;
        }
        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_SENSE_RAW_INPUT_1) {
        if (strict && (inputs == NULL || in_dim <= 1))
            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;
        if (!strict) {
            next_output = (in_dim > 1 && inputs) ?
                inputs[1] * parameters->param1 : 0.0;
        } else {
            const double source = inputs[1];
            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;
            next_output = source * parameters->param1;
        }
        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_SENSE_RAW_INPUT_2) {
        if (strict && (inputs == NULL || in_dim <= 2))
            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;
        if (!strict) {
            next_output = (in_dim > 2 && inputs) ?
                inputs[2] * parameters->param1 : 0.0;
        } else {
            const double source = inputs[2];
            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;
            next_output = source * parameters->param1;
        }
        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_SENSE_RAW_INPUT_3) {
        if (strict && (inputs == NULL || in_dim <= 3))
            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;
        if (!strict) {
            next_output = (in_dim > 3 && inputs) ?
                inputs[3] * parameters->param1 : 0.0;
        } else {
            const double source = inputs[3];
            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;
            next_output = source * parameters->param1;
        }
        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_SENSE_CHANNEL) {
        if (strict && (inputs == NULL || parameters->channel >= in_dim))
            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;
        if (!strict) {
            next_output = (parameters->channel < in_dim && inputs) ?
                inputs[parameters->channel] * parameters->param1 : 0.0;
        } else {
            const double source = inputs[parameters->channel];
            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;
            next_output = source * parameters->param1;
        }
        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_OP_DELAY_N) {
        const size_t read_idx = ((size_t)next_delay_index + 16u -
            (size_t)parameters->delay_ticks) & 15u;
        next_output = next_delay[read_idx];
        next_delay[next_delay_index & 15u] = in0;
        next_delay_index = (uint8_t)((next_delay_index + 1u) & 15u);
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_ACT_PRIMARY_POSITIVE || cell_type == SDSC_CELL_ACT_PRIMARY_NEGATIVE || cell_type == SDSC_CELL_ACT_DEFENSIVE_RESET || cell_type == SDSC_CELL_ACT_IMMUNE_BLOCK || cell_type == SDSC_CELL_ACT_CHANNEL || cell_type == SDSC_CELL_PREDICT_SENSE_0 || cell_type == SDSC_CELL_PREDICT_SENSE_1) {
        next_output = in0;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_OP_QUADRATIC) {
        next_output = parameters->param1 * in0 * in0 +
            parameters->param2 * in0 * in1;
        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_GATE_HYSTERESIS) {
        if (in0 > parameters->param1) next_latch = true;
        else if (in0 < parameters->param2) next_latch = false;
        next_output = next_latch ? 1.0 : -1.0;
        next_state = next_output;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_GATE_THRESHOLD) {
        next_output = (in0 > parameters->param1) ? 1.0 : 0.0;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_GATE_DEADZONE) {
        next_output = (fabs(in0) > fabs(parameters->param1)) ? in0 : 0.0;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_GATE_MIN_MAX) {
        next_output = (parameters->param1 > 0.5) ?
            (in0 < in1 ? in1 : in0) : (in1 < in0 ? in1 : in0);
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_OP_EMA) {
        if (!strict) {
            if (!isfinite(in0)) in0 = 0.0;
            if (!isfinite(next_state)) next_state = 0.0;
        }
        const double alpha = sdsc_cell_kernel_clamp_double(
            parameters->param1, 0.001, 1.0);
        if (strict && !*initialized) next_state = in0;
        else if (!strict && state->activation_count == 0) next_state = in0;
        else next_state = alpha * in0 + (1.0 - alpha) * next_state;
        next_output = next_state;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_OP_DIFF) {
        next_output = in0 - next_previous;
        next_previous = in0;
        goto sdsc_cell_kernel_commit;
    }

    if (cell_type == SDSC_CELL_OP_OSCILLATOR) {
        if ((!strict && state->activation_count == 0 && fabs(next_state) < 1e-6 &&
             fabs(next_aux) < 1e-6) ||
            (strict && !*initialized && fabs(next_state) < 1e-6 &&
             fabs(next_aux) < 1e-6)) next_state = 0.1;
        const double mu = (fabs(parameters->param1) > 1e-4) ?
            sdsc_cell_kernel_clamp_double(fabs(parameters->param1), 0.01, 5.0) : 1.0;
        const double dt = (fabs(parameters->param2) > 1e-4) ?
            sdsc_cell_kernel_clamp_double(fabs(parameters->param2), 0.001, 0.2) : 0.05;
        const double ds1 = next_aux;
        const double ds2 = mu * (1.0 - next_state * next_state) * next_aux -
            next_state + in0;
        const double raw_next_state = next_state + ds1 * dt;
        const double raw_next_aux = next_aux + ds2 * dt;
        if (strict && (!isfinite(ds1) || !isfinite(ds2) ||
            !isfinite(raw_next_state) || !isfinite(raw_next_aux)))
            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        next_state = sdsc_cell_kernel_clamp_double(raw_next_state, -10.0, 10.0);
        next_aux = sdsc_cell_kernel_clamp_double(raw_next_aux, -10.0, 10.0);
        next_output = next_state;
        if (strict && (!isfinite(next_state) || !isfinite(next_aux) ||
            !isfinite(next_output))) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        goto sdsc_cell_kernel_commit;
    }

    {
        const uint8_t op = sdsc_cell_type_to_legacy_eval_op(cell_type);
        float s = 0.0f;
        float a = 0.0f;
        float g = 0.0f;
        float x = 0.0f;
        bool folded_input = false;
        if (!strict) {
            s = (float)next_state;
            a = (float)next_aux;
            g = (float)parameters->param1;
            x = (float)in0;
            if (!isfinite(s)) s = 0.0f;
            if (!isfinite(a)) a = 0.0f;
            if (!isfinite(g)) g = 1.0f;
            if (!isfinite(x)) x = 0.0f;
        } else {
            if (!sdsc_cell_kernel_strict_double_to_float(next_state, &s) ||
                !sdsc_cell_kernel_strict_double_to_float(next_aux, &a) ||
                !sdsc_cell_kernel_strict_double_to_float(parameters->param1, &g))
                return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        }
        if (cell_type == SDSC_CELL_OP_SUM) {
            const double folded = in0 + in1;
            folded_input = true;
            if (strict) {
                if (!sdsc_cell_kernel_strict_double_to_float(folded, &x))
                    return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
            } else {
                x = (float)folded;
            }
        }
        if (cell_type == SDSC_CELL_OP_SUB) {
            const double folded = in0 - in1;
            folded_input = true;
            if (strict) {
                if (!sdsc_cell_kernel_strict_double_to_float(folded, &x))
                    return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
            } else {
                x = (float)folded;
            }
        }
        if (cell_type == SDSC_CELL_OP_MULTIPLY) {
            const double folded = in0 * in1;
            folded_input = true;
            if (strict) {
                if (!sdsc_cell_kernel_strict_double_to_float(folded, &x))
                    return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
            } else {
                x = (float)folded;
            }
        }
        if (strict && !folded_input &&
            !sdsc_cell_kernel_strict_double_to_float(in0, &x))
            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        if (!strict && !isfinite(x)) x = 0.0f;
        bool primitive_valid = true;
        float out = sdsc_primitive_eval_profile(op, g, x, &s, &a,
            strict, &primitive_valid);
        if (strict && !primitive_valid)
            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        if (!strict) {
            if (!isfinite(s)) s = 0.0f;
            if (!isfinite(out)) out = 0.0f;
        } else if (!isfinite(s) || !isfinite(a) || !isfinite(out)) {
            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        }
        const SdscCellKernelBounds bounds = sdsc_cell_kernel_bounds(op);
        s = sdsc_cell_kernel_clamp_float(s, bounds.state_min, bounds.state_max);
        out = sdsc_cell_kernel_clamp_float(out, bounds.out_min, bounds.out_max);
        if (strict && (!isfinite(s) || !isfinite(a) || !isfinite(out)))
            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        next_state = (double)s;
        next_aux = (double)a;
        next_output = (double)out;
    }

sdsc_cell_kernel_commit:
    if (strict && (!isfinite(next_state) || !isfinite(next_aux) ||
        !isfinite(next_previous) || !isfinite(next_output) || next_delay_index >= 16u))
        return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
    if (strict) {
        for (size_t i = 0; i < 16u; ++i) {
            if (!isfinite(next_delay[i])) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;
        }
    }
    *state->state_val = next_state;
    *state->aux_state = next_aux;
    *state->prev_input = next_previous;
    *state->output_val = next_output;
    for (size_t i = 0; i < 16u; ++i) state->delay_buffer[i] = next_delay[i];
    *state->latch_state = next_latch;
    *state->delay_idx = next_delay_index;
    if (strict) *initialized = true;
    return SDSC_CELL_KERNEL_OK;
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step_profile(
    SdscCellKernelProfile profile, uint8_t cell_type,
    SdscCellKernelStrictParameters parameters, double in0, double in1,
    size_t in_dim, const double* inputs,
    SdscCellKernelStrictStateView* strict_state) {
    if (profile != SDSC_CELL_KERNEL_PROFILE_STRICT_CORE)
        return SDSC_CELL_KERNEL_INVALID_PROFILE;
    if (!sdsc_cell_type_is_valid(cell_type) || strict_state == NULL ||
        strict_state->state_val == NULL || strict_state->aux_state == NULL ||
        strict_state->prev_input == NULL || strict_state->output_val == NULL ||
        strict_state->delay_buffer == NULL || strict_state->latch_state == NULL ||
        strict_state->delay_idx == NULL || strict_state->initialized == NULL)
        return sdsc_cell_type_is_valid(cell_type) ? SDSC_CELL_KERNEL_INVALID_ARGUMENT :
            SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;
    SdscCellKernelNormalizedParameters normalized;
    const SdscCellKernelStatus normalized_status =
        sdsc_cell_kernel_normalize_strict_parameters(cell_type, &parameters, &normalized);
    if (normalized_status != SDSC_CELL_KERNEL_OK) return normalized_status;
    SdscCellKernelStateView base = {
        strict_state->state_val, strict_state->aux_state, strict_state->prev_input,
        strict_state->output_val, strict_state->delay_buffer, strict_state->latch_state,
        strict_state->delay_idx, 0u};
    return sdsc_cell_kernel_step_common(cell_type, &normalized, in0, in1,
        in_dim, inputs, &base, true, strict_state->initialized);
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step_strict(
    uint8_t cell_type, const SdscCellKernelStrictParameters* parameters,
    double in0, double in1, size_t in_dim, const double* inputs,
    SdscCellKernelStrictStateView* strict_state) {
    if (parameters == NULL) return SDSC_CELL_KERNEL_INVALID_ARGUMENT;
    return sdsc_cell_kernel_step_profile(
        SDSC_CELL_KERNEL_PROFILE_STRICT_CORE, cell_type, *parameters,
        in0, in1, in_dim, inputs, strict_state);
}

SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step(
    uint8_t cell_type, double param1, double param2, double in0, double in1,
    size_t in_dim, const double* inputs, SdscCellKernelStateView* state) {
    if (!sdsc_cell_type_is_valid(cell_type)) return SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;
    if (state == NULL || state->state_val == NULL || state->aux_state == NULL ||
        state->prev_input == NULL || state->output_val == NULL ||
        state->delay_buffer == NULL || state->latch_state == NULL || state->delay_idx == NULL)
        return SDSC_CELL_KERNEL_INVALID_ARGUMENT;
    SdscCellKernelNormalizedParameters normalized = {param1, param2, 0u, 0};
    if (cell_type == SDSC_CELL_SENSE_CHANNEL && param2 >= 0.0) {
        if (!isfinite(param2) || floor(param2) >= ldexp(1.0,
            (int)(sizeof(size_t) * CHAR_BIT))) return SDSC_CELL_KERNEL_INVALID_PARAMETER;
        normalized.channel = (size_t)floor(param2);
    }
    if (cell_type == SDSC_CELL_OP_DELAY_N &&
        !sdsc_cell_kernel_normalize_delay(param1, &normalized.delay_ticks))
        return SDSC_CELL_KERNEL_INVALID_PARAMETER;
    return sdsc_cell_kernel_step_common(cell_type, &normalized, in0, in1,
        in_dim, inputs, state, false, NULL);
}

#undef SDSC_CELL_KERNEL_INLINE

#endif /* KUN_CELLULAR_SDSC_CELL_KERNEL_H_ */
