/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */

#ifndef KUN_CELLULAR_SDSC_PRIMITIVES_H_
#define KUN_CELLULAR_SDSC_PRIMITIVES_H_

#include <math.h>
#include <stdint.h>

#if defined(__GNUC__) || defined(__clang__)
#define SDSC_INLINE static inline __attribute__((always_inline))
#else
#define SDSC_INLINE static inline
#endif

/* 27 大完备原子计算原语类型枚举 (5-bit 紧凑硬件操作码) */
typedef enum {
    SDSC_OP_SENSE_0          = 0,   /* 原始输入通道 0 (透传直连) */
    SDSC_OP_SENSE_1          = 1,   /* 原始输入通道 1 (透传直连) */
    SDSC_OP_SENSE_2          = 2,   /* 原始输入通道 2 (透传直连) */
    SDSC_OP_SENSE_3          = 3,   /* 原始输入通道 3 (透传直连) */
    SDSC_OP_SUM              = 4,   /* 线性叠加直通 (Pure Sum): out = x (双端口折叠由调用方完成, 增益无关) */
    SDSC_OP_INTEGRATE        = 5,   /* 稳态误差积分累加器 (Leaky Integrator): s = 0.85*s + 0.15*x, out = tanh(s * g) */
    SDSC_OP_AMPLIFY          = 6,   /* 敏捷高增益兴奋门: tanh(x * g * 2.5) */
    SDSC_OP_INVERT           = 7,   /* 反相负反馈抑制门: -tanh(x * g) */
    SDSC_OP_DAMPER           = 8,   /* 惯性一阶低通阻尼滤波: s = 0.70*s + 0.30*x, out = s */
    SDSC_OP_CLIP             = 9,   /* 区间硬饱和截断: clamp(x * g, -1.0, 1.0) */
    SDSC_OP_ABS              = 10,   /* 绝对值全波整流能量提取: |tanh(x * g)| */
    SDSC_OP_MULTIPLY         = 11,   /* 乘法直通 (Pure Multiply): out = x (in0*in1 折叠由调用方完成) */
    SDSC_OP_DIFF             = 12,   /* 一阶时间差分/微分 (PD阻尼基石): out = x - s, s = x */
    SDSC_OP_SUB              = 13,   /* 差分直通 (Pure Sub): out = x (in0-in1 折叠由调用方完成) */
    SDSC_OP_RATIO            = 14,   /* 相对比率有界归一化: s = 0.85*s + 0.15*|x|, out = clamp(x / (s + 0.1), -2.0, 2.0) */
    SDSC_OP_THRESHOLD        = 15,   /* 阶跃决策硬门 (参数化): x > g ? 1 : 0 (g=阈值) */
    SDSC_OP_HYSTERESIS       = 16,   /* 施密特对称双阈值迟滞 (参数化): x>g=>1, x<-g=>-1 (g=半窗宽) */
    SDSC_OP_DEADZONE         = 17,   /* 中心死区噪声门 (参数化): |x|>|g| ? x : 0 (g=死区半宽) */
    SDSC_OP_INHIBIT          = 18,   /* 侧向抑制与能量闭锁: s = 0.80*s + 0.20*|x|, out = tanh(x*g) * max(0.0, 1.0 - s) */
    SDSC_OP_AND              = 19,   /* 时空协同兴奋与门: (x > 0 && s > 0) ? 1.0 : 0.0, s = x */
    SDSC_OP_MIN_MAX          = 20,   /* 时序极值包络提取门: out = max(x, s), s = x */
    SDSC_OP_ACT_POS          = 21,   /* 正向单极性执行器: clamp(x * g, 0.0, 1.0) */
    SDSC_OP_ACT_NEG          = 22,   /* 负向单极性执行器: clamp(-x * g, 0.0, 1.0) */
    SDSC_OP_ACT_RESET        = 23,   /* 防御性归零复位门: |x| < 0.10 ? 0.0 : x */
    SDSC_OP_CORRELATION      = 24,   /* 时空自相关注意力核: s = 0.90*s + (x*a)*0.10, a = x, out = tanh(s * g) */
    SDSC_OP_FATIGUE          = 25,   /* 神经元代谢适应疲劳门: s = min(2.0, s + |x|*0.15)*0.96, out = tanh(x*g) / (1.0 + s) */
    SDSC_OP_PASSTHRU         = 26,   /* 直通透传通道: out = x */
    SDSC_OP_ACCUMULATOR      = 27   /* 真积分累加器 (Pure Accumulator): s = clamp(s + x*g, -16, 16), out = s (时序工作记忆核) */
} SdscOpType;

/**
 * 核心原语单步前向推演函数 (无堆分配、纯浮点寄存器、李雅普诺夫有界保证)
 * 
 * @param op_type  原语算子枚举
 * @param g        可演化增益参数 (gain)
 * @param x        当前输入突触加权和
 * @param state    细胞私有累积状态槽 1 (指针，原位读写)
 * @param aux      细胞私有辅助状态槽 2 (指针，原位读写)
 * @return float   本拍单步激发输出 u(t)
 */
SDSC_INLINE float sdsc_primitive_eval(
    uint8_t op_type,
    float g,
    float x,
    float* state,
    float* aux
) {
    float out = 0.0f;
    float s = *state;
    float a = *aux;

    switch (op_type) {
        case SDSC_OP_SENSE_0: { // opcode 0
            out = x;
            break;
        }
        case SDSC_OP_SENSE_1: { // opcode 1
            out = x;
            break;
        }
        case SDSC_OP_SENSE_2: { // opcode 2
            out = x;
            break;
        }
        case SDSC_OP_SENSE_3: { // opcode 3
            out = x;
            break;
        }
        case SDSC_OP_SUM: { // opcode 4
            out = x;
            break;
        }
        case SDSC_OP_INTEGRATE: { // opcode 5
            s = s * 0.85f + x * 0.15f;
            out = tanhf(s * g);
            break;
        }
        case SDSC_OP_AMPLIFY: { // opcode 6
            out = tanhf(x * g * 2.5f);
            break;
        }
        case SDSC_OP_INVERT: { // opcode 7
            out = -tanhf(x * g);
            break;
        }
        case SDSC_OP_DAMPER: { // opcode 8
            s = s * 0.70f + x * 0.30f;
            out = s;
            break;
        }
        case SDSC_OP_CLIP: { // opcode 9
            out = fminf(fmaxf(x * g, -1.0f), 1.0f);
            break;
        }
        case SDSC_OP_ABS: { // opcode 10
            out = fabsf(tanhf(x * g));
            break;
        }
        case SDSC_OP_MULTIPLY: { // opcode 11
            out = x;
            break;
        }
        case SDSC_OP_DIFF: { // opcode 12
            out = x - s;
            s = x;
            break;
        }
        case SDSC_OP_SUB: { // opcode 13
            out = x;
            break;
        }
        case SDSC_OP_RATIO: { // opcode 14
            s = s * 0.85f + fabsf(x) * 0.15f;
            out = fminf(fmaxf(x / (s + 0.1f), -2.0f), 2.0f);
            break;
        }
        case SDSC_OP_THRESHOLD: { // opcode 15
            out = (x > g) ? 1.0f : 0.0f;
            break;
        }
        case SDSC_OP_HYSTERESIS: { // opcode 16
            if (x > g) s = 1.0f;
            else if (x < -g) s = -1.0f;
            out = s;
            break;
        }
        case SDSC_OP_DEADZONE: { // opcode 17
            out = (fabsf(x) > fabsf(g)) ? x : 0.0f;
            break;
        }
        case SDSC_OP_INHIBIT: { // opcode 18
            s = s * 0.80f + fabsf(x) * 0.20f;
            out = tanhf(x * g) * fmaxf(0.0f, 1.0f - s);
            break;
        }
        case SDSC_OP_AND: { // opcode 19
            out = (x > 0.0f && s > 0.0f) ? 1.0f : 0.0f;
            s = x;
            break;
        }
        case SDSC_OP_MIN_MAX: { // opcode 20
            out = fmaxf(x, s);
            s = x;
            break;
        }
        case SDSC_OP_ACT_POS: { // opcode 21
            out = fminf(fmaxf(x * g, 0.0f), 1.0f);
            break;
        }
        case SDSC_OP_ACT_NEG: { // opcode 22
            out = fminf(fmaxf(-x * g, 0.0f), 1.0f);
            break;
        }
        case SDSC_OP_ACT_RESET: { // opcode 23
            out = (fabsf(x) < 0.10f) ? 0.0f : x;
            break;
        }
        case SDSC_OP_CORRELATION: { // opcode 24
            s = s * 0.90f + (x * a) * 0.10f;
            a = x;
            out = tanhf(s * g);
            break;
        }
        case SDSC_OP_FATIGUE: { // opcode 25
            s = fminf(2.0f, s + fabsf(x) * 0.15f) * 0.96f;
            out = tanhf(x * g) / (1.0f + s);
            break;
        }
        case SDSC_OP_PASSTHRU: { // opcode 26
            out = x;
            break;
        }
        case SDSC_OP_ACCUMULATOR: { // opcode 27
            s = fminf(fmaxf(s + x * g, -16.0f), 16.0f);
            out = s;
            break;
        }
        default:
            out = x;
            break;
    }

    *state = s;
    *aux   = a;
    return out;
}

/* 包含全图反向伴随方程与直通梯度 (VJP) 算子头文件 */
#include "sdsc_primitives_vjp.h"

#endif /* KUN_CELLULAR_SDSC_PRIMITIVES_H_ */
