/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */

#ifndef KUN_CELLULAR_CORE_PRIMITIVE_CONTRACT_HPP_
#define KUN_CELLULAR_CORE_PRIMITIVE_CONTRACT_HPP_

#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <optional>
#include <span>
#include <type_traits>
#include <variant>
#include "kun/cellular/core/semantic_profile.hpp"
#include "kun/cellular/generated_ops.hpp"

namespace kun::core {

enum class ParameterSlot : uint8_t { Param1 = 0, Param2 = 1 };
enum class ParameterKind : uint8_t { Continuous, ChannelIndex, DelayTicks, Enum, Unused };
enum class ParameterValueType : uint8_t { Continuous, ChannelIndex, DelayTicks, MinMaxMode, Unused };
enum class StateField : uint8_t { StateValue, AuxState, PreviousInput, DelayBuffer, DelayIndex, LatchState };
enum class InitializationDependency : uint8_t { None, StateValue, ActivityCount };
enum class VjpCapability : uint8_t { Exact, ApproximateOrSTE, Unsupported };
enum class ExecutionPolicy : uint8_t {
    DefaultLeaf,        // float conversion, finite sanitize, mapped primitive, PrimitiveBounds post-clamp
    SpecialDouble,      // legacy double branch with branch-local transforms; no generic leaf post-clamp
    GenericPassthrough, // legacy double in0 pass-through; no gain or primitive clamp
};
enum class ResetAction : uint8_t { Unused, Zero, FalseValue };
enum class StrictExecutionStatus : uint8_t {
    Unsupported,  // no native strict cell-kernel execution
    Implemented,  // strict shared cell kernel only; graph executors remain separate
};

struct ResetMetadata {
    ResetAction state_value;
    ResetAction aux_state;
    ResetAction previous_input;
    ResetAction delay_buffer;
    ResetAction delay_index;
    ResetAction latch_state;
    ResetAction activation_count;
    ResetAction output_value;
};

struct ParameterDescriptor {
    const char* name;
    ParameterSlot slot;
    ParameterKind kind;
    ParameterValueType value_type;
    const char* legacy_mapping;
    double search_min;
    double search_max;
    bool has_search_domain;
    bool finite_only;
    bool trainable_continuous;
};

struct CellContract {
    CellType type;
    uint8_t code;
    const char* name;
    uint8_t input_port_count;
    const char* input_semantics;
    const char* output_contract;
    uint8_t mapped_opcode;
    PrimitiveBounds mapped_bounds;
    ExecutionPolicy execution_policy;
    std::array<ParameterDescriptor, 2> parameters;
    std::array<StateField, 2> state_fields;
    uint8_t state_field_count;
    InitializationDependency initialization_dependency;
    const char* first_step_semantics;
    bool legacy_state_dependency;
    ResetMetadata reset;
    SemanticProfile semantic_profile;
    uint32_t semantic_version;
    StrictExecutionStatus strict_execution;
    VjpCapability vjp_capability;
};

struct ContinuousValue {
    double value;
};
struct ChannelIndex {
    std::size_t value;
    explicit constexpr ChannelIndex(std::size_t v) : value(v) {}
};
struct DelayTicks {
    uint64_t value;
    explicit constexpr DelayTicks(uint64_t v) : value(v) {}
};
enum class MinMaxMode : uint8_t { Min = 0, Max = 1 };
struct UnusedParameter {};
using ParameterValue = std::variant<ContinuousValue, ChannelIndex, DelayTicks, MinMaxMode, UnusedParameter>;
struct ContinuousParameterList {
    std::array<ParameterSlot, 2> slots{};
    uint8_t count = 0;
};

inline constexpr ParameterValue parameter_value_for_channel(ChannelIndex value) { return value; }
inline constexpr ParameterValue parameter_value_for_delay(DelayTicks value) { return value; }
inline constexpr ParameterValue parameter_value_for_continuous(ContinuousValue value) { return value; }

inline std::span<const CellContract> all_cell_contracts();

inline const CellContract* find_cell_contract(uint8_t code) {
    for (const auto& contract : all_cell_contracts()) {
        if (contract.code == code) return &contract;
    }
    return nullptr;
}

inline std::optional<std::reference_wrapper<const CellContract>> contract_for(CellType type) {
    for (const auto& contract : all_cell_contracts()) {
        if (contract.type == type) return std::cref(contract);
    }
    return std::nullopt;
}

inline std::optional<std::reference_wrapper<const CellContract>> contract_for_code(uint8_t code) {
    if (const auto* contract = find_cell_contract(code)) return std::cref(*contract);
    return std::nullopt;
}

inline std::optional<std::reference_wrapper<const CellContract>> contract_for_code(
    uint8_t code, uint8_t profile_code) {
    if (!semantic_profile_from_code(profile_code)) return std::nullopt;
    return contract_for_code(code);
}

inline std::optional<std::reference_wrapper<const CellContract>> contract_for_code(
    uint8_t code, SemanticProfile profile) {
    return contract_for_code(code, static_cast<uint8_t>(profile));
}

inline StrictExecutionStatus strict_execution_status(const CellContract& contract) {
    return contract.strict_execution;
}

inline bool is_continuous_trainable(const ParameterDescriptor& descriptor) {
    return descriptor.kind == ParameterKind::Continuous && descriptor.trainable_continuous;
}

inline ContinuousParameterList continuous_trainable_parameters(const CellContract& contract) {
    ContinuousParameterList result;
    for (const auto& descriptor : contract.parameters) {
        if (is_continuous_trainable(descriptor)) {
            result.slots[result.count++] = descriptor.slot;
        }
    }
    return result;
}

inline std::optional<ContinuousValue> make_continuous(
    const ParameterDescriptor& descriptor, double value) {
    if (descriptor.kind != ParameterKind::Continuous || !descriptor.finite_only ||
        !std::isfinite(value)) {
        return std::nullopt;
    }
    return ContinuousValue{value};
}

inline std::optional<ChannelIndex> make_channel_index(
    const ParameterDescriptor& descriptor, std::size_t value) {
    if (descriptor.kind != ParameterKind::ChannelIndex || descriptor.value_type != ParameterValueType::ChannelIndex) {
        return std::nullopt;
    }
    return ChannelIndex{value};
}

inline std::optional<DelayTicks> make_delay_ticks(
    const ParameterDescriptor& descriptor, int value) {
    if (descriptor.kind != ParameterKind::DelayTicks || descriptor.value_type != ParameterValueType::DelayTicks ||
        value < 1 || value > 16) {
        return std::nullopt;
    }
    return DelayTicks{static_cast<uint64_t>(value)};
}

inline std::optional<MinMaxMode> make_min_max_mode(
    const ParameterDescriptor& descriptor, MinMaxMode value) {
    if (descriptor.kind != ParameterKind::Enum || descriptor.value_type != ParameterValueType::MinMaxMode) {
        return std::nullopt;
    }
    if (value != MinMaxMode::Min && value != MinMaxMode::Max) return std::nullopt;
    return value;
}

inline bool is_valid_min_max_mode(MinMaxMode value) {
    return value == MinMaxMode::Min || value == MinMaxMode::Max;
}

inline bool parameter_value_matches(
    const ParameterDescriptor& descriptor, const ParameterValue& value) {
    // Intentional type-only check; validate_parameter checks domains and enum values.
    switch (descriptor.value_type) {
        case ParameterValueType::Continuous: return std::holds_alternative<ContinuousValue>(value);
        case ParameterValueType::ChannelIndex: return std::holds_alternative<ChannelIndex>(value);
        case ParameterValueType::DelayTicks: return std::holds_alternative<DelayTicks>(value);
        case ParameterValueType::MinMaxMode: return std::holds_alternative<MinMaxMode>(value);
        case ParameterValueType::Unused: return std::holds_alternative<UnusedParameter>(value);
    }
    return false;
}

inline bool validate_parameter(
    const ParameterDescriptor& descriptor, const ParameterValue& value) {
    switch (descriptor.value_type) {
        case ParameterValueType::Continuous:
            return std::holds_alternative<ContinuousValue>(value) &&
                make_continuous(descriptor, std::get<ContinuousValue>(value).value).has_value();
        case ParameterValueType::ChannelIndex:
            return std::holds_alternative<ChannelIndex>(value) &&
                descriptor.kind == ParameterKind::ChannelIndex;
        case ParameterValueType::DelayTicks:
            return std::holds_alternative<DelayTicks>(value) &&
                std::get<DelayTicks>(value).value <= 16 &&
                make_delay_ticks(descriptor, static_cast<int>(std::get<DelayTicks>(value).value)).has_value();
        case ParameterValueType::MinMaxMode:
            return std::holds_alternative<MinMaxMode>(value) &&
                make_min_max_mode(descriptor, std::get<MinMaxMode>(value)).has_value();
        case ParameterValueType::Unused:
            return std::holds_alternative<UnusedParameter>(value) &&
                descriptor.kind == ParameterKind::Unused;
    }
    return false;
}

inline const std::array<CellContract, 30> CELL_CONTRACTS = {{
    {CellType::SENSE_RAW_INPUT_0, 0, "SENSE_RAW_INPUT_0", 0, "external input channel 0", "inputs[0] * param1", cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_0), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_0)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the receptor gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::SENSE_RAW_INPUT_1, 1, "SENSE_RAW_INPUT_1", 0, "external input channel 1", "inputs[1] * param1", cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_1), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_1)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the receptor gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::SENSE_RAW_INPUT_2, 2, "SENSE_RAW_INPUT_2", 0, "external input channel 2", "inputs[2] * param1", cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_2), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_2)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the receptor gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::SENSE_RAW_INPUT_3, 3, "SENSE_RAW_INPUT_3", 0, "external input channel 3", "inputs[3] * param1", cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_3), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::SENSE_RAW_INPUT_3)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the receptor gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::SENSE_CHANNEL, 4, "SENSE_CHANNEL", 0, "external input channel selected by param2", "inputs[channel_index] * param1", cell_type_to_sdsc_eval_op(CellType::SENSE_CHANNEL), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::SENSE_CHANNEL)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 scales the selected external channel", 0, 4, true, true, true}, {"channel", ParameterSlot::Param2, ParameterKind::ChannelIndex, ParameterValueType::ChannelIndex, "legacy floor(param2), negative values select channel 0", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_EMA, 10, "OP_EMA", 1, "in0", "state_val", cell_type_to_sdsc_eval_op(CellType::OP_EMA), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_EMA)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"alpha", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "clamp(param1, 0.001, 1.0)", 0.001, 1, true, true, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 1, InitializationDependency::ActivityCount, "activation_count==0 seeds state_val from in0", true, ResetMetadata{ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Unsupported},
    {CellType::OP_DIFF, 11, "OP_DIFF", 1, "in0", "in0 - previous_input", cell_type_to_sdsc_eval_op(CellType::OP_DIFF), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_DIFF)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by the special legacy dispatch", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::PreviousInput, StateField::StateValue}}, 1, InitializationDependency::StateValue, "previous_input starts at its stored legacy value", true, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_INTEGRAL, 12, "OP_INTEGRAL", 1, "in0", "clamp(state_val + in0 * param1, -16, 16)", cell_type_to_sdsc_eval_op(CellType::OP_INTEGRAL), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_INTEGRAL)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "legacy dispatch uses SDSC_OP_ACCUMULATOR with gain param1", -4, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 1, InitializationDependency::StateValue, "accumulates from stored state_val; no activation-count seed", false, ResetMetadata{ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_SUM, 13, "OP_SUM", 2, "in0 and in1 are folded before the leaf primitive", "sdsc SUM leaf receives (in0 + in1) and passes it through; gain is ignored", cell_type_to_sdsc_eval_op(CellType::OP_SUM), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_SUM)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by SDSC_OP_SUM", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_SUB, 14, "OP_SUB", 2, "in0 and in1 are folded before the leaf primitive", "sdsc SUB leaf receives (in0 - in1) and passes it through; gain is ignored", cell_type_to_sdsc_eval_op(CellType::OP_SUB), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_SUB)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by SDSC_OP_SUB", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_MULTIPLY, 15, "OP_MULTIPLY", 2, "in0 and in1 are folded before the leaf primitive", "sdsc MULTIPLY leaf receives (in0 * in1) and passes it through; gain is ignored", cell_type_to_sdsc_eval_op(CellType::OP_MULTIPLY), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_MULTIPLY)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by SDSC_OP_MULTIPLY", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_RATIO, 16, "OP_RATIO", 1, "in0; normalization uses the private state, not in1", "clamp(in0 / (0.85*state_val + 0.15*abs(in0) + 0.1), -2, 2)", cell_type_to_sdsc_eval_op(CellType::OP_RATIO), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_RATIO)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by the ratio primitive", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 1, InitializationDependency::StateValue, "state_val is updated from the prior state", false, ResetMetadata{ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_ABS, 17, "OP_ABS", 1, "in0", "abs(tanh(in0 * param1))", cell_type_to_sdsc_eval_op(CellType::OP_ABS), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_ABS)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the primitive gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::OP_DELAY_N, 18, "OP_DELAY_N", 1, "in0", "delay_buffer[(delay_index - delay_ticks) mod 16]", cell_type_to_sdsc_eval_op(CellType::OP_DELAY_N), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_DELAY_N)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"delay", ParameterSlot::Param1, ParameterKind::DelayTicks, ParameterValueType::DelayTicks, "legacy clamp(floor(param1*16), 1, 16)", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::DelayBuffer, StateField::DelayIndex}}, 2, InitializationDependency::StateValue, "zero-initialized 16-slot legacy ring buffer", true, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Unsupported},
    {CellType::OP_OSCILLATOR, 19, "OP_OSCILLATOR", 1, "in0 forcing term", "state_val after legacy Van der Pol step", cell_type_to_sdsc_eval_op(CellType::OP_OSCILLATOR), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_OSCILLATOR)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"mu", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "abs(param1) then clamp to [0.01, 5.0], default 1.0", 0.01, 5, true, true, false}, {"dt", ParameterSlot::Param2, ParameterKind::Continuous, ParameterValueType::Continuous, "abs(param2) then clamp to [0.001, 0.2], default 0.05", 0.001, 0.20000000000000001, true, true, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::AuxState}}, 2, InitializationDependency::ActivityCount, "activation_count==0 and zero state seeds state_val=0.1", true, ResetMetadata{ResetAction::Zero, ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Unsupported},
    {CellType::OP_QUADRATIC, 20, "OP_QUADRATIC", 2, "in0 and in1", "param1*in0*in0 + param2*in0*in1", cell_type_to_sdsc_eval_op(CellType::OP_QUADRATIC), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::OP_QUADRATIC)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"square_gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 multiplies in0 squared", -4, 4, true, true, false}, {"cross_gain", ParameterSlot::Param2, ParameterKind::Continuous, ParameterValueType::Continuous, "param2 multiplies in0*in1", -4, 4, true, true, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Unsupported},
    {CellType::GATE_THRESHOLD, 24, "GATE_THRESHOLD", 1, "in0", "in0 > param1 ? 1 : 0", cell_type_to_sdsc_eval_op(CellType::GATE_THRESHOLD), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::GATE_THRESHOLD)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"threshold", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the threshold", 0.0, 0.0, false, true, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::GATE_HYSTERESIS, 25, "GATE_HYSTERESIS", 1, "in0", "latch_state: high when in0 > param1, low when in0 < param2", cell_type_to_sdsc_eval_op(CellType::GATE_HYSTERESIS), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::GATE_HYSTERESIS)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"high_threshold", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "special legacy branch compares in0 > param1", 0.0, 0.0, false, true, false}, {"low_threshold", ParameterSlot::Param2, ParameterKind::Continuous, ParameterValueType::Continuous, "special legacy branch compares in0 < param2", 0.0, 0.0, false, true, false}}}, std::array<StateField, 2>{{StateField::LatchState, StateField::StateValue}}, 2, InitializationDependency::StateValue, "after reset output_val is 0; first in0 evaluation below high threshold yields -1", true, ResetMetadata{ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::FalseValue, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Unsupported},
    {CellType::GATE_AND, 26, "GATE_AND", 1, "in0; the second predicate is legacy state_val, not in1", "(in0 > 0 && state_val > 0) ? 1 : 0", cell_type_to_sdsc_eval_op(CellType::GATE_AND), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::GATE_AND)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by SDSC_OP_AND", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 1, InitializationDependency::StateValue, "state_val is tested before being replaced by in0", true, ResetMetadata{ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::GATE_INHIBIT, 27, "GATE_INHIBIT", 1, "in0; inhibition state is legacy state_val, not in1", "tanh(in0 * param1) * max(0, 1 - state_val)", cell_type_to_sdsc_eval_op(CellType::GATE_INHIBIT), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::GATE_INHIBIT)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the primitive gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 1, InitializationDependency::StateValue, "state_val updates by the primitive's inhibition accumulator", false, ResetMetadata{ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::GATE_DEADZONE, 28, "GATE_DEADZONE", 1, "in0", "abs(in0) > abs(param1) ? in0 : 0", cell_type_to_sdsc_eval_op(CellType::GATE_DEADZONE), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::GATE_DEADZONE)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"deadband", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is used by the primitive as the deadband threshold", 0.0, 0.0, false, true, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
    {CellType::GATE_MIN_MAX, 29, "GATE_MIN_MAX", 2, "in0 and in1", "param1 selects max(in0,in1) when Max, otherwise min(in0,in1)", cell_type_to_sdsc_eval_op(CellType::GATE_MIN_MAX), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::GATE_MIN_MAX)), ExecutionPolicy::SpecialDouble, std::array<ParameterDescriptor, 2>{{{"mode", ParameterSlot::Param1, ParameterKind::Enum, ParameterValueType::MinMaxMode, "param1 > 0.5 selects max, otherwise min", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state in the special legacy branch", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Unsupported},
    {CellType::ACT_PRIMARY_POSITIVE, 30, "ACT_PRIMARY_POSITIVE", 1, "in0", "in0 (generic legacy effector pass-through)", cell_type_to_sdsc_eval_op(CellType::ACT_PRIMARY_POSITIVE), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::ACT_PRIMARY_POSITIVE)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch; no gain is applied", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "fixed effector channel is selected outside dispatch", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::ACT_PRIMARY_NEGATIVE, 31, "ACT_PRIMARY_NEGATIVE", 1, "in0", "in0 (generic legacy effector pass-through)", cell_type_to_sdsc_eval_op(CellType::ACT_PRIMARY_NEGATIVE), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::ACT_PRIMARY_NEGATIVE)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch; no gain is applied", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "fixed effector channel is selected outside dispatch", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::ACT_DEFENSIVE_RESET, 32, "ACT_DEFENSIVE_RESET", 1, "in0", "in0 (generic legacy effector pass-through)", cell_type_to_sdsc_eval_op(CellType::ACT_DEFENSIVE_RESET), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::ACT_DEFENSIVE_RESET)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "fixed effector channel is selected outside dispatch", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::ACT_IMMUNE_BLOCK, 33, "ACT_IMMUNE_BLOCK", 1, "in0", "in0 (generic legacy effector pass-through)", cell_type_to_sdsc_eval_op(CellType::ACT_IMMUNE_BLOCK), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::ACT_IMMUNE_BLOCK)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "fixed effector channel is selected outside dispatch", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::ACT_CHANNEL, 34, "ACT_CHANNEL", 1, "in0", "in0; action channel selection is carried by param2 outside dispatch", cell_type_to_sdsc_eval_op(CellType::ACT_CHANNEL), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::ACT_CHANNEL)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch; no gain is applied", 0.0, 0.0, false, false, false}, {"channel", ParameterSlot::Param2, ParameterKind::ChannelIndex, ParameterValueType::ChannelIndex, "legacy floor(param2) selects the external action channel", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::PREDICT_SENSE_0, 40, "PREDICT_SENSE_0", 1, "in0 from the internal prediction path", "in0 (generic legacy pass-through)", cell_type_to_sdsc_eval_op(CellType::PREDICT_SENSE_0), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::PREDICT_SENSE_0)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::PREDICT_SENSE_1, 41, "PREDICT_SENSE_1", 1, "in0 from the internal prediction path", "in0 (generic legacy pass-through)", cell_type_to_sdsc_eval_op(CellType::PREDICT_SENSE_1), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::PREDICT_SENSE_1)), ExecutionPolicy::GenericPassthrough, std::array<ParameterDescriptor, 2>{{{"unused", ParameterSlot::Param1, ParameterKind::Unused, ParameterValueType::Unused, "ignored by dispatch", 0.0, 0.0, false, false, false}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::StateValue}}, 0, InitializationDependency::None, "no private state", false, ResetMetadata{ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::Exact},
    {CellType::ASSOCIATION_HUB, 42, "ASSOCIATION_HUB", 1, "in0", "tanh(state_val * param1) after correlation state update", cell_type_to_sdsc_eval_op(CellType::ASSOCIATION_HUB), get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::ASSOCIATION_HUB)), ExecutionPolicy::DefaultLeaf, std::array<ParameterDescriptor, 2>{{{"gain", ParameterSlot::Param1, ParameterKind::Continuous, ParameterValueType::Continuous, "param1 is the correlation primitive gain", 0, 4, true, true, true}, {"unused", ParameterSlot::Param2, ParameterKind::Unused, ParameterValueType::Unused, "ignored", 0.0, 0.0, false, false, false}}}, std::array<StateField, 2>{{StateField::StateValue, StateField::AuxState}}, 2, InitializationDependency::StateValue, "correlation state and aux_state use stored legacy values", false, ResetMetadata{ResetAction::Zero, ResetAction::Zero, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Unused, ResetAction::Zero, ResetAction::Zero}, SemanticProfile::LegacyCompatible, 1, StrictExecutionStatus::Implemented, VjpCapability::ApproximateOrSTE},
}};

inline std::span<const CellContract> all_cell_contracts() {
    return CELL_CONTRACTS;
}

} // namespace kun::core

#endif /* KUN_CELLULAR_CORE_PRIMITIVE_CONTRACT_HPP_ */
