#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KunCellular Unified Primitive Code Generator (tools/gen_ops.py)
Single Source of Truth: include/kun/cellular/ops.yaml
Generates:
  1. include/kun/cellular/sdsc_primitives.h   (Pure C11 inline execution)
  2. include/kun/cellular/cuda_ops.cuh        (CUDA device inline function & NVRTC JIT string)
  3. include/kun/cellular/generated_ops.hpp   (C++20 enums, stringifiers, validators, metadata)
  4. tools/kun_cellular_ops.py                (Python runtime dictionary and parity tables)
"""

import sys
import os
import argparse
import yaml

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OPS_YAML_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "ops.yaml")
C11_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "sdsc_primitives.h")
CUDA_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "cuda_ops.cuh")
CPP_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "generated_ops.hpp")
PY_OUT_PATH = os.path.join(REPO_ROOT, "tools", "kun_cellular_ops.py")

AUTO_GEN_BANNER = """/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */
"""

def load_ops_spec():
    with open(OPS_YAML_PATH, "r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    return spec

def generate_c11_header(spec):
    prims = spec["sdsc_primitives"]
    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_SDSC_PRIMITIVES_H_",
        "#define KUN_CELLULAR_SDSC_PRIMITIVES_H_",
        "",
        "#include <math.h>",
        "#include <stdint.h>",
        "",
        "#if defined(__GNUC__) || defined(__clang__)",
        "#define SDSC_INLINE static inline __attribute__((always_inline))",
        "#else",
        "#define SDSC_INLINE static inline",
        "#endif",
        "",
        "/* 26 大完备原子计算原语类型枚举 (5-bit 紧凑硬件操作码) */",
        "typedef enum {"
    ]

    for i, p in enumerate(prims):
        sep = "," if i < len(prims) - 1 else ""
        lines.append(f"    {p['name']:<24} = {p['id']}{sep}   /* {p['description']} */")

    lines.extend([
        "} SdscOpType;",
        "",
        "/**",
        " * 核心原语单步前向推演函数 (无堆分配、纯浮点寄存器、李雅普诺夫有界保证)",
        " * ",
        " * @param op_type  原语算子枚举",
        " * @param g        可演化增益参数 (gain)",
        " * @param x        当前输入突触加权和",
        " * @param state    细胞私有累积状态槽 1 (指针，原位读写)",
        " * @param aux      细胞私有辅助状态槽 2 (指针，原位读写)",
        " * @return float   本拍单步激发输出 u(t)",
        " */",
        "SDSC_INLINE float sdsc_primitive_eval(",
        "    uint8_t op_type,",
        "    float g,",
        "    float x,",
        "    float* state,",
        "    float* aux",
        ") {",
        "    float out = 0.0f;",
        "    float s = *state;",
        "    float a = *aux;",
        "",
        "    switch (op_type) {"
    ])

    for p in prims:
        lines.append(f"        case {p['name']}: {{ // opcode {p['id']}")
        eval_body = p['eval_code'].strip()
        for b_line in eval_body.splitlines():
            lines.append(f"            {b_line}")
        lines.append("            break;")
        lines.append("        }")

    lines.extend([
        "        default:",
        "            out = x;",
        "            break;",
        "    }",
        "",
        "    *state = s;",
        "    *aux   = a;",
        "    return out;",
        "}",
        "",
        "#endif /* KUN_CELLULAR_SDSC_PRIMITIVES_H_ */",
        ""
    ])
    return "\n".join(lines)

def generate_cuda_header(spec):
    prims = spec["sdsc_primitives"]
    
    # 构造核心 __device__ 内联函数源码
    device_func_lines = [
        "__device__ __forceinline__ float sdsc_cuda_eval_primitive(",
        "    uint8_t op,",
        "    float gain,",
        "    float x,",
        "    float* state,",
        "    float* aux",
        ") {",
        "    float out = 0.0f;",
        "    float s = *state;",
        "    float a = *aux;",
        "    float g = gain;",
        "",
        "    switch (op) {"
    ]

    for p in prims:
        device_func_lines.append(f"        case {p['id']}: {{ // {p['name']}")
        eval_body = p['eval_code'].strip()
        for b_line in eval_body.splitlines():
            device_func_lines.append(f"            {b_line}")
        device_func_lines.append("            break;")
        device_func_lines.append("        }")

    device_func_lines.extend([
        "        default:",
        "            out = x;",
        "            break;",
        "    }",
        "",
        "    *state = s;",
        "    *aux   = a;",
        "    return out;",
        "}"
    ])
    device_func_lines_str = "\n".join(device_func_lines)

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_CUDA_OPS_CUH_",
        "#define KUN_CELLULAR_CUDA_OPS_CUH_",
        "",
        "#include <stdint.h>",
        "#include <math.h>",
        "",
        "#if defined(__CUDACC__) || defined(__CUDA_ARCH__)",
        "#define SDSC_CUDA_DEVICE __device__ __forceinline__",
        "#else",
        "#define SDSC_CUDA_DEVICE inline",
        "#endif",
        "",
        "SDSC_CUDA_DEVICE float sdsc_cuda_eval_primitive(",
        "    uint8_t op,",
        "    float gain,",
        "    float x,",
        "    float* state,",
        "    float* aux",
        ") {",
        "    float out = 0.0f;",
        "    float s = *state;",
        "    float a = *aux;",
        "    float g = gain;",
        "",
        "    switch (op) {"
    ]

    for p in prims:
        lines.append(f"        case {p['id']}: {{ // {p['name']}")
        eval_body = p['eval_code'].strip()
        for b_line in eval_body.splitlines():
            lines.append(f"            {b_line}")
        lines.append("            break;")
        lines.append("        }")

    lines.extend([
        "        default:",
        "            out = x;",
        "            break;",
        "    }",
        "",
        "    *state = s;",
        "    *aux   = a;",
        "    return out;",
        "}",
        "",
        "// NVRTC JIT 动态内核代码注入模板字符串 (消除手写 CUDA JIT 源码漂移)",
        "static const char* const SDSC_CUDA_DEVICE_OPS_SRC = R\"(",
        device_func_lines_str,
        ")\";",
        "",
        "#endif /* KUN_CELLULAR_CUDA_OPS_CUH_ */",
        ""
    ])
    return "\n".join(lines)

def generate_cpp_header(spec):
    prims = spec["sdsc_primitives"]
    cells = spec["cell_types"]

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_GENERATED_OPS_HPP_",
        "#define KUN_CELLULAR_GENERATED_OPS_HPP_",
        "",
        "#include <cstdint>",
        "#include <string>",
        "#include <string_view>",
        "#include <array>",
        "#include <algorithm>",
        "",
        "namespace kun {",
        "",
        "// ============================================================================",
        "// 1. 软件定义硅基细胞计算机 (SDSCC) 硬件原子原语枚举",
        "// ============================================================================",
        "enum class SdscOpType : uint8_t {"
    ]

    for i, p in enumerate(prims):
        sep = "," if i < len(prims) - 1 else ""
        lines.append(f"    {p['name']} = {p['id']}{sep}")

    lines.extend([
        "};",
        "",
        "// ============================================================================",
        "// 2. 形态学细胞类型 (CellType): 生物计算原语完整枚举",
        "// ============================================================================",
        "enum class CellType : uint8_t {"
    ])

    for i, c in enumerate(cells):
        sep = "," if i < len(cells) - 1 else ""
        lines.append(f"    {c['name']:<24} = {c['code']}{sep}   // {c['description']}")

    lines.extend([
        "};",
        "",
        "// ============================================================================",
        "// 3. 字符串名称双向转换与形态学元数据反射",
        "// ============================================================================",
        "inline const char* to_string(CellType t) {",
        "    switch (t) {"
    ])

    for c in cells:
        lines.append(f"        case CellType::{c['name']}: return \"{c['str_name']}\";")

    lines.extend([
        "        default: return \"Cell_Unknown\";",
        "    }",
        "}",
        "",
        "inline CellType cell_type_from_string(std::string_view name) {"
    ])

    for c in cells:
        lines.append(f"    if (name == \"{c['str_name']}\") return CellType::{c['name']};")

    lines.extend([
        "    return CellType::OP_EMA;",
        "}",
        "",
        "inline bool is_receptor_cell(CellType t) {",
        "    switch (t) {"
    ])

    for c in cells:
        if c["category"] == "RECEPTOR":
            lines.append(f"        case CellType::{c['name']}:")

    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        "",
        "inline bool is_effector_cell(CellType t) {",
        "    switch (t) {"
    ])

    for c in cells:
        if c["category"] == "EFFECTOR":
            lines.append(f"        case CellType::{c['name']}:")

    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        "",
        "inline bool is_valid_cell_type_code(uint8_t op) {",
        "    switch (static_cast<CellType>(op)) {"
    ])

    for c in cells:
        lines.append(f"        case CellType::{c['name']}:")

    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        "",
        "inline uint8_t cell_type_to_sdsc_opcode(CellType t) {",
        "    return static_cast<uint8_t>(t);",
        "}",
        "",
        "inline CellType sdsc_opcode_to_cell_type(uint8_t op, uint8_t flags = 0, uint32_t version = 3) {",
        "    if (version >= 3) {",
        "        if (is_valid_cell_type_code(op)) {",
        "            return static_cast<CellType>(op);",
        "        }",
        "    }",
        "    // 兼容历史 v1/v2 检查点反序列化解码",
        "    if (flags & 0x01) {",
        "        if (op == 0) return CellType::SENSE_RAW_INPUT_0;",
        "        if (op == 1) return CellType::SENSE_RAW_INPUT_1;",
        "        if (op == 2) return CellType::SENSE_RAW_INPUT_2;",
        "        if (op == 3) return CellType::SENSE_RAW_INPUT_3;",
        "        return CellType::SENSE_CHANNEL;",
        "    }",
        "    if (flags & 0x02) {",
        "        if (op == 21) return CellType::ACT_PRIMARY_POSITIVE;",
        "        if (op == 22) return CellType::ACT_PRIMARY_NEGATIVE;",
        "        if (op == 23) return CellType::ACT_DEFENSIVE_RESET;",
        "        return CellType::ACT_CHANNEL;",
        "    }",
        "    switch (op) {"
    ])

    # 历史遗留 opcode 映射
    legacy_map = {
        0: "SENSE_RAW_INPUT_0", 1: "SENSE_RAW_INPUT_1", 2: "SENSE_RAW_INPUT_2", 3: "SENSE_RAW_INPUT_3",
        4: "OP_SUM", 5: "OP_INTEGRAL", 8: "OP_EMA", 10: "OP_ABS", 11: "OP_MULTIPLY", 12: "OP_DIFF",
        13: "OP_SUB", 14: "OP_RATIO", 15: "GATE_THRESHOLD", 16: "GATE_HYSTERESIS", 17: "GATE_DEADZONE",
        18: "GATE_INHIBIT", 19: "GATE_AND", 20: "GATE_MIN_MAX",
        21: "ACT_PRIMARY_POSITIVE", 22: "ACT_PRIMARY_NEGATIVE", 23: "ACT_DEFENSIVE_RESET",
        24: "ASSOCIATION_HUB", 25: "OP_OSCILLATOR"
    }
    for op_val, cell_name in legacy_map.items():
        lines.append(f"        case {op_val}: return CellType::{cell_name};")

    lines.extend([
        "        default: return CellType::OP_EMA;",
        "    }",
        "}",
        "",
        "// 硬件原语静态反射元数据",
        "struct PrimitiveMeta {",
        "    uint8_t id;",
        "    const char* name;",
        "    const char* category;",
        "    bool has_state;",
        "    bool has_aux;",
        "    float default_p1;",
        "    float default_p2;",
        "    const char* lyapunov_bound;",
        "};",
        "",
        f"inline constexpr std::array<PrimitiveMeta, {len(prims)}> SDSC_PRIMITIVES_META = {{{{",
    ])

    for p in prims:
        has_s = "true" if p['has_state'] else "false"
        has_a = "true" if p['has_aux'] else "false"
        lines.append(f'    {{{p["id"]}, "{p["name"]}", "{p["category"]}", {has_s}, {has_a}, {p["default_p1"]}f, {p["default_p2"]}f, "{p["lyapunov_bound"]}"}},')

    lines.extend([
        "}};",
        "",
        "} // namespace kun",
        "",
        "#endif /* KUN_CELLULAR_GENERATED_OPS_HPP_ */",
        ""
    ])
    return "\n".join(lines)

AUTO_GEN_BANNER_PY = """# ============================================================================
# THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
# FROM include/kun/cellular/ops.yaml.
# DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
# ============================================================================
"""

def generate_python_module(spec):
    prims = spec["sdsc_primitives"]
    cells = spec["cell_types"]

    lines = [
        '# -*- coding: utf-8 -*-',
        AUTO_GEN_BANNER_PY.strip(),
        '"""',
        'SDSCC Operator and Cell Type Definitions for Python',
        '"""',
        '',
        'class SdscOp:',
    ]
    for p in prims:
        lines.append(f"    {p['name']} = {p['id']}")

    lines.extend([
        '',
        'class CellType:',
    ])
    for c in cells:
        lines.append(f"    {c['name']} = {c['code']}")

    lines.extend([
        '',
        'CELL_TYPE_TO_STR = {',
    ])
    for c in cells:
        lines.append(f"    CellType.{c['name']}: '{c['str_name']}',")
    lines.extend([
        '}',
        '',
        'STR_TO_CELL_TYPE = {v: k for k, v in CELL_TYPE_TO_STR.items()}',
        '',
        'PRIMITIVES_META = [',
    ])
    for p in prims:
        lines.append(f"    {{'id': {p['id']}, 'name': '{p['name']}', 'category': '{p['category']}', "
                     f"'has_state': {p['has_state']}, 'has_aux': {p['has_aux']}, "
                     f"'default_p1': {p['default_p1']}, 'default_p2': {p['default_p2']}, "
                     f"'lyapunov_bound': '{p['lyapunov_bound']}'}},")
    lines.append(']')
    lines.append('')
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="SDSCC Primitive Code Generator")
    parser.add_argument("--check", action="store_true", help="Check if generated files are up to date without writing")
    args = parser.parse_args()

    spec = load_ops_spec()
    c11_code = generate_c11_header(spec)
    cuda_code = generate_cuda_header(spec)
    cpp_code = generate_cpp_header(spec)
    py_code = generate_python_module(spec)

    targets = [
        (C11_OUT_PATH, c11_code),
        (CUDA_OUT_PATH, cuda_code),
        (CPP_OUT_PATH, cpp_code),
        (PY_OUT_PATH, py_code),
    ]

    if args.check:
        out_of_date = []
        for path, code in targets:
            if not os.path.exists(path):
                out_of_date.append((path, "File does not exist"))
                continue
            with open(path, "r", encoding="utf-8") as f:
                existing = f.read()
            if existing != code:
                out_of_date.append((path, "Content mismatch"))

        if out_of_date:
            print("ERROR: Generated operator files are OUT OF DATE with ops.yaml:")
            for p, reason in out_of_date:
                print(f"  - {os.path.relpath(p, REPO_ROOT)}: {reason}")
            print("Run 'python3 tools/gen_ops.py' to regenerate them.")
            sys.exit(1)
        else:
            print("SUCCESS: All operator headers match ops.yaml perfectly.")
            sys.exit(0)

    # 写入生成文件
    for path, code in targets:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"[gen_ops] Generated: {os.path.relpath(path, REPO_ROOT)}")

    print("[gen_ops] Successfully generated all single-source-of-truth operator headers!")

if __name__ == "__main__":
    main()
