#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
KunCellular Unified Primitive Code Generator (tools/gen_ops.py)
Single Source of Truth: include/kun/cellular/ops.yaml
Generates:
  1. include/kun/cellular/sdsc_primitives.h       (Pure C11 inline execution)
  2. include/kun/cellular/sdsc_primitives_vjp.h   (Pure C11 inline VJP backward & STE)
  3. include/kun/cellular/cuda_ops.cuh            (CUDA device inline function & NVRTC JIT string)
  4. include/kun/cellular/cuda_ops_vjp.cuh        (CUDA device inline VJP & NVRTC JIT string)
  5. include/kun/cellular/generated_ops.hpp       (C++20 enums, bounds, differentiability, reflection)
  6. tools/kun_cellular_ops.py                    (Python runtime dictionary, VJP & parity tables)
"""

import sys
import os
import argparse
import math
import yaml

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OPS_YAML_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "ops.yaml")
C11_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "sdsc_primitives.h")
C11_VJP_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "sdsc_primitives_vjp.h")
CUDA_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "cuda_ops.cuh")
CUDA_VJP_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "cuda_ops_vjp.cuh")
CPP_OUT_PATH = os.path.join(REPO_ROOT, "include", "kun", "cellular", "generated_ops.hpp")
PY_OUT_PATH = os.path.join(REPO_ROOT, "tools", "kun_cellular_ops.py")
CONTRACT_OUT_PATH = os.path.join(
    REPO_ROOT, "include", "kun", "cellular", "core", "primitive_contract.hpp"
)
CELL_KERNEL_OUT_PATH = os.path.join(
    REPO_ROOT, "include", "kun", "cellular", "sdsc_cell_kernel.h"
)

AUTO_GEN_BANNER = """/* ============================================================================
 * THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
 * FROM include/kun/cellular/ops.yaml.
 * DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
 * ============================================================================
 */
"""

def load_ops_spec():
    with open(OPS_YAML_PATH, "r", encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    validate_ops_spec(spec)
    return spec


def _contract_error(index, cell, message):
    name = cell.get("name", "<missing-name>") if isinstance(cell, dict) else "<non-map>"
    code = cell.get("code", "<missing-code>") if isinstance(cell, dict) else "<non-map>"
    raise ValueError(f"cell_types[{index}] {name} (code {code}): {message}")


def validate_ops_spec(spec):
    if not isinstance(spec, dict) or not isinstance(spec.get("sdsc_primitives"), list):
        raise ValueError("spec: sdsc_primitives must be a list")
    primitives = spec["sdsc_primitives"]
    primitive_names = set()
    primitive_ids = set()
    for index, primitive in enumerate(primitives):
        if not isinstance(primitive, dict):
            raise ValueError(f"sdsc_primitives[{index}]: entry must be a mapping")
        name = primitive.get("name")
        primitive_id = primitive.get("id")
        if not isinstance(name, str) or not name:
            raise ValueError(f"sdsc_primitives[{index}]: missing name")
        if name in primitive_names:
            raise ValueError(f"sdsc_primitives[{index}] {name}: duplicate primitive name")
        if type(primitive_id) is not int or primitive_id in primitive_ids:
            raise ValueError(f"sdsc_primitives[{index}] {name}: duplicate or invalid primitive id")
        primitive_names.add(name)
        primitive_ids.add(primitive_id)

    cells = spec.get("cell_types")
    if not isinstance(cells, list):
        raise ValueError("cell_types: must be a list")
    cell_codes = set()
    cell_names = set()
    allowed_kinds = {"continuous", "channel_index", "delay_ticks", "enum", "unused"}
    allowed_value_types = {"Continuous", "ChannelIndex", "DelayTicks", "MinMaxMode", "Unused"}
    allowed_state_fields = {
        "state_val", "aux_state", "previous_input", "delay_buffer",
        "delay_index", "latch_state",
    }
    allowed_initialization = {"none", "state_zero", "activity_count"}
    allowed_vjp = {"exact", "approximate_or_ste", "unsupported"}
    allowed_execution_policies = {"default_leaf", "special_double", "generic_passthrough"}
    allowed_kernel_kinds = {
        "receptor_fixed", "receptor_channel", "ema", "diff", "delay",
        "oscillator", "quadratic", "threshold", "hysteresis", "deadzone", "minmax",
        "passthrough", "default_leaf", "default_sum", "default_sub",
        "default_multiply",
    }
    allowed_reset_actions = {"unused", "zero", "false"}
    reset_fields = (
        "state_value", "aux_state", "previous_input", "delay_buffer",
        "delay_index", "latch_state", "activation_count", "output_value",
    )
    for index, cell in enumerate(cells):
        if not isinstance(cell, dict):
            _contract_error(index, {}, "entry must be a mapping")
        name = cell.get("name")
        code = cell.get("code")
        if not isinstance(name, str) or not name:
            _contract_error(index, cell, "missing name")
        if type(code) is not int or not 0 <= code <= 255:
            _contract_error(index, cell, "code must be an integer")
        if code in cell_codes:
            _contract_error(index, cell, "duplicate cell code")
        if name in cell_names:
            _contract_error(index, cell, "duplicate cell name")
        cell_codes.add(code)
        cell_names.add(name)
        if cell.get("sdsc_op") not in primitive_names:
            _contract_error(index, cell, f"unknown mapped opcode {cell.get('sdsc_op')!r}")
        if cell.get("legacy_eval_op") not in primitive_names:
            _contract_error(index, cell, f"unknown legacy evaluation opcode {cell.get('legacy_eval_op')!r}")
        legacy_kernel = cell.get("legacy_kernel")
        if not isinstance(legacy_kernel, dict) or legacy_kernel.get("kind") not in allowed_kernel_kinds:
            _contract_error(index, cell, "malformed legacy_kernel metadata")
        if legacy_kernel["kind"] == "receptor_fixed":
            if type(legacy_kernel.get("channel")) is not int or not 0 <= legacy_kernel["channel"] <= 3:
                _contract_error(index, cell, "receptor_fixed channel must be 0..3")
        elif "channel" in legacy_kernel:
            _contract_error(index, cell, "only receptor_fixed may declare channel")

        contract = cell.get("contract")
        if not isinstance(contract, dict):
            _contract_error(index, cell, "missing contract")
        inputs = contract.get("inputs")
        if not isinstance(inputs, dict) or type(inputs.get("count")) is not int or not (
            0 <= inputs["count"] <= 2
        ) or not isinstance(inputs.get("semantics"), str) or not inputs["semantics"]:
            _contract_error(index, cell, "malformed inputs contract")
        if not isinstance(contract.get("output"), str) or not contract["output"]:
            _contract_error(index, cell, "malformed output contract")

        parameters = contract.get("parameters")
        if not isinstance(parameters, list) or len(parameters) != 2:
            _contract_error(index, cell, "parameters must describe param1 and param2 exactly")
        slots = set()
        for parameter_index, parameter in enumerate(parameters):
            if not isinstance(parameter, dict):
                _contract_error(index, cell, f"parameter {parameter_index} must be a mapping")
            slot = parameter.get("slot")
            if slot not in {"param1", "param2"} or slot in slots:
                _contract_error(index, cell, f"parameter {parameter_index} has invalid/duplicate slot")
            slots.add(slot)
            if not isinstance(parameter.get("name"), str) or not parameter["name"]:
                _contract_error(index, cell, f"{slot} has malformed name")
            kind = parameter.get("kind")
            value_type = parameter.get("value_type")
            if kind not in allowed_kinds:
                _contract_error(index, cell, f"{slot} has invalid kind {kind!r}")
            if value_type not in allowed_value_types:
                _contract_error(index, cell, f"{slot} has invalid value_type {value_type!r}")
            expected_types = {
                "continuous": "Continuous",
                "channel_index": "ChannelIndex",
                "delay_ticks": "DelayTicks",
                "enum": "MinMaxMode",
                "unused": "Unused",
            }
            if expected_types[kind] != value_type:
                _contract_error(index, cell, f"{slot} kind/value_type mismatch")
            if not isinstance(parameter.get("legacy_mapping"), str) or not parameter["legacy_mapping"]:
                _contract_error(index, cell, f"{slot} has malformed legacy_mapping")
            if type(parameter.get("trainable_continuous")) is not bool:
                _contract_error(index, cell, f"{slot} has malformed trainable_continuous")
            if kind != "continuous" and parameter["trainable_continuous"]:
                _contract_error(index, cell, f"{slot} cannot be trainable_continuous for kind {kind}")
            domain = parameter.get("domain")
            if kind != "continuous" and parameter.get("search_domain") is not None:
                _contract_error(index, cell, f"{slot} search_domain is only valid for continuous parameters")
            if kind == "unused" or kind == "channel_index":
                if domain is not None:
                    _contract_error(index, cell, f"{slot} must not declare a numeric domain")
            elif kind == "enum":
                if not isinstance(domain, dict) or domain.get("values") != ["Min", "Max"]:
                    _contract_error(index, cell, f"{slot} enum domain must be [Min, Max]")
            elif kind == "continuous":
                if domain != "finite":
                    _contract_error(index, cell, f"{slot} continuous domain must be 'finite'")
                search_domain = parameter.get("search_domain")
                if search_domain is not None:
                    if not isinstance(search_domain, dict):
                        _contract_error(index, cell, f"{slot} search_domain must be a mapping")
                    lower = search_domain.get("min")
                    upper = search_domain.get("max")
                    if not all(type(value) in (int, float) and math.isfinite(float(value))
                               for value in (lower, upper)):
                        _contract_error(index, cell, f"{slot} search_domain bounds must be finite numbers")
                    if float(lower) > float(upper):
                        _contract_error(index, cell, f"{slot} search_domain min exceeds max")
            else:
                if not isinstance(domain, dict):
                    _contract_error(index, cell, f"{slot} requires a numeric domain")
                lower = domain.get("min")
                upper = domain.get("max")
                if not all(type(value) in (int, float) and math.isfinite(float(value))
                           for value in (lower, upper)):
                    _contract_error(index, cell, f"{slot} domain bounds must be finite numbers")
                if float(lower) > float(upper):
                    _contract_error(index, cell, f"{slot} domain min exceeds max")
                if kind == "delay_ticks" and (lower, upper) != (1, 16):
                    _contract_error(index, cell, f"{slot} delay domain must be exactly [1, 16]")

        state = contract.get("state")
        if not isinstance(state, dict):
            _contract_error(index, cell, "missing state contract")
        fields = state.get("fields")
        if not isinstance(fields, list) or len(fields) > 2 or any(
            field not in allowed_state_fields for field in fields
        ):
            _contract_error(index, cell, "malformed state fields")
        if state.get("initialization") not in allowed_initialization:
            _contract_error(index, cell, "malformed state initialization")
        if not isinstance(state.get("first_step"), str) or not state["first_step"]:
            _contract_error(index, cell, "malformed first_step semantics")
        if not isinstance(state.get("legacy_dependency"), bool):
            _contract_error(index, cell, "malformed legacy_dependency")
        reset = contract.get("reset")
        if not isinstance(reset, dict) or set(reset) != set(reset_fields):
            _contract_error(index, cell, "reset must describe all reset fields")
        if any(reset[field] not in allowed_reset_actions for field in reset_fields):
            _contract_error(index, cell, "reset contains an invalid action")
        if not isinstance(contract.get("execution_policy"), str) or (
            contract["execution_policy"] not in allowed_execution_policies
        ):
            _contract_error(index, cell, "malformed execution_policy")
        if contract.get("vjp_capability") == "exact" and (
            contract["execution_policy"] != "generic_passthrough"
        ):
            _contract_error(index, cell, "exact VJP requires generic_passthrough backend support")
        if contract.get("semantic_profile") not in {"LegacyCompatible", "StrictCore"}:
            _contract_error(index, cell, "unknown semantic profile")
        if type(contract.get("semantic_version")) is not int or contract.get("semantic_version") != 1:
            _contract_error(index, cell, "unsupported or missing semantic_version")
        if contract.get("strict_execution") not in {"defined_not_executable", "implemented"}:
            _contract_error(index, cell, "strict_execution must distinguish metadata from execution")
        if contract.get("vjp_capability") not in allowed_vjp:
            _contract_error(index, cell, "malformed vjp_capability")

    if len(cells) != len(cell_codes) or len(cells) != len(cell_names):
        raise ValueError("cell_types: duplicate code or name")

def generate_c11_header(spec):
    prims = spec["sdsc_primitives"]
    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_SDSC_PRIMITIVES_H_",
        "#define KUN_CELLULAR_SDSC_PRIMITIVES_H_",
        "",
        "#include <math.h>",
        "#include <stdbool.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#if defined(__GNUC__) || defined(__clang__)",
        "#define SDSC_INLINE static inline __attribute__((always_inline))",
        "#else",
        "#define SDSC_INLINE static inline",
        "#endif",
        "",
        "/* 27 大完备原子计算原语类型枚举 (5-bit 紧凑硬件操作码) */",
        "typedef enum {"
    ]

    for i, p in enumerate(prims):
        sep = "," if i < len(prims) - 1 else ""
        lines.append(f"    {p['name']:<24} = {p['id']}{sep}   /* {p['description']} */")

    lines.extend([
        "} SdscOpType;",
        "",
        "/* The strict policy uses the same generated equation switch as legacy.",
        " * It validates intermediates before saturating/clamping operators can mask",
        " * non-finite values; legacy calls keep the original success behavior. */",
        "SDSC_INLINE float sdsc_primitive_eval_profile(",
        "    uint8_t op_type,",
        "    float g,",
        "    float x,",
        "    float* state,",
        "    float* aux,",
        "    bool strict,",
        "    bool* valid",
        ") {",
        "    float out = 0.0f;",
        "    float s = *state;",
        "    float a = *aux;",
        "    bool ok = true;",
        "",
        "#define SDSC_STRICT_CHECK_FINITE(value) \\",
        "    do { if (strict && !isfinite(value)) { ok = false; goto sdsc_primitive_invalid; } } while (0)",
        "#define SDSC_STRICT_CHECK_NONZERO(value) \\",
        "    do { if (strict && (value) == 0.0f) { ok = false; goto sdsc_primitive_invalid; } } while (0)",
        "",
        "    switch (op_type) {"
    ])

    for p in prims:
        lines.append(f"        case {p['name']}: {{ // opcode {p['id']}")
        eval_body = str(p['eval_code']).strip()
        for b_line in eval_body.splitlines():
            lines.append(f"            {b_line}")
        lines.append("            break;")
        lines.append("        }")

    lines.extend([
        "        default:",
        "            out = x;",
        "            break;",
        "    }",
        "",
        "sdsc_primitive_invalid:",
        "#undef SDSC_STRICT_CHECK_NONZERO",
        "#undef SDSC_STRICT_CHECK_FINITE",
        "",
        "    *state = s;",
        "    *aux   = a;",
        "    if (valid != NULL) *valid = ok;",
        "    return out;",
        "}",
        "",
        "SDSC_INLINE float sdsc_primitive_eval(",
        "    uint8_t op_type,",
        "    float g,",
        "    float x,",
        "    float* state,",
        "    float* aux",
        ") {",
        "    return sdsc_primitive_eval_profile(op_type, g, x, state, aux, false, NULL);",
        "}",
        "",
        "/* 包含全图反向伴随方程与直通梯度 (VJP) 算子头文件 */",
        '#include "sdsc_primitives_vjp.h"',
        "",
        "#endif /* KUN_CELLULAR_SDSC_PRIMITIVES_H_ */",
        ""
    ])
    return "\n".join(lines)

def generate_c11_vjp_header(spec):
    prims = spec["sdsc_primitives"]
    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_SDSC_PRIMITIVES_VJP_H_",
        "#define KUN_CELLULAR_SDSC_PRIMITIVES_VJP_H_",
        "",
        "#include <math.h>",
        "#include <stdint.h>",
        "#include <stdbool.h>",
        "",
        "#if defined(__GNUC__) || defined(__clang__)",
        "#define SDSC_INLINE static inline __attribute__((always_inline))",
        "#else",
        "#define SDSC_INLINE static inline",
        "#endif",
        "",
        "/* 反向向量-雅可比积 (Vector-Jacobian Product) 偏导返回包 (纯寄存器传递) */",
        "typedef struct {",
        "    float dx;       /* 突触输入梯度 dL/dx */",
        "    float ds_prev;  /* 前向输入状态偏导 dL/ds(t-1) */",
        "    float da_prev;  /* 前向输入辅助状态偏导 dL/da(t-1) */",
        "    float dg;       /* 算子增益参数偏导 dL/dg */",
        "} SdscOpVJP;",
        "",
        "/**",
        " * 核心原语反向向量-雅可比积 (VJP) 计算",
        " * 用于全图 BPTT 伴随反向回传与非可微原语直通门控 (STE)",
        " * ",
        " * @param op_type  原语算子枚举",
        " * @param g        算子增益参数",
        " * @param x        当前步输入",
        " * @param s        当前步前向初态",
        " * @param a        当前步前向初辅助态",
        " * @param out      当前步前向输出",
        " * @param s_next   当前步前向终态",
        " * @param a_next   当前步前向终辅助态",
        " * @param dy       上游传回的输出梯度 dL/dout",
        " * @param ds_next  沿时间反传的状态梯度 dL/ds_next",
        " * @param da_next  沿时间反传的辅助状态梯度 dL/da_next",
        " * @return SdscOpVJP 输入、状态与参数梯度",
        " */",
        "SDSC_INLINE SdscOpVJP sdsc_primitive_vjp(",
        "    uint8_t op_type,",
        "    float g,",
        "    float x,",
        "    float s,",
        "    float a,",
        "    float out,",
        "    float s_next,",
        "    float a_next,",
        "    float dy,",
        "    float ds_next,",
        "    float da_next",
        ") {",
        "    SdscOpVJP ret;",
        "    float dx = 0.0f;",
        "    float ds_prev = 0.0f;",
        "    float da_prev = 0.0f;",
        "    float dg = 0.0f;",
        "",
        "    switch (op_type) {"
    ]

    for p in prims:
        vjp_code = p.get("vjp_code", "").strip()
        lines.append(f"        case {p['id']}: {{ // {p['name']}")
        for b_line in vjp_code.splitlines():
            lines.append(f"            {b_line}")
        lines.append("            break;")
        lines.append("        }")

    lines.extend([
        "        default:",
        "            dx = dy;",
        "            break;",
        "    }",
        "",
        "    ret.dx = dx;",
        "    ret.ds_prev = ds_prev;",
        "    ret.da_prev = da_prev;",
        "    ret.dg = dg;",
        "    return ret;",
        "}",
        "",
        "#endif /* KUN_CELLULAR_SDSC_PRIMITIVES_VJP_H_ */",
        ""
    ])
    return "\n".join(lines)

def generate_cuda_header(spec):
    prims = spec["sdsc_primitives"]
    device_func_lines = [
        "__device__ __forceinline__ float sdsc_cuda_eval_primitive(",
        "    uint8_t op,",
        "    float gain,",
        "    float x,",
        "    float* state,",
        "    float* aux",
        ") {",
        "    float out = 0.0f;",
        "    float s = *state;",
        "    float a = *aux;",
        "    float g = gain;",
        "",
        "    switch (op) {"
    ]

    for p in prims:
        device_func_lines.append(f"        case {p['id']}: {{ // {p['name']}")
        eval_body = str(p['eval_code']).strip()
        for b_line in eval_body.splitlines():
            if "SDSC_STRICT_CHECK_" not in b_line:
                device_func_lines.append(f"            {b_line}")
        device_func_lines.append("            break;")
        device_func_lines.append("        }")

    device_func_lines.extend([
        "        default:",
        "            out = x;",
        "            break;",
        "    }",
        "",
        "    *state = s;",
        "    *aux   = a;",
        "    return out;",
        "}"
    ])
    device_func_lines_str = "\n".join(device_func_lines)

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_CUDA_OPS_CUH_",
        "#define KUN_CELLULAR_CUDA_OPS_CUH_",
        "",
        "#include <stdint.h>",
        "#include <math.h>",
        "",
        "#if defined(__CUDACC__) || defined(__CUDA_ARCH__)",
        "#define SDSC_CUDA_DEVICE __device__ __forceinline__",
        "#else",
        "#define SDSC_CUDA_DEVICE inline",
        "#endif",
        "",
        "SDSC_CUDA_DEVICE float sdsc_cuda_eval_primitive(",
        "    uint8_t op,",
        "    float gain,",
        "    float x,",
        "    float* state,",
        "    float* aux",
        ") {",
        "    float out = 0.0f;",
        "    float s = *state;",
        "    float a = *aux;",
        "    float g = gain;",
        "",
        "    switch (op) {"
    ]

    for p in prims:
        lines.append(f"        case {p['id']}: {{ // {p['name']}")
        eval_body = str(p['eval_code']).strip()
        for b_line in eval_body.splitlines():
            if "SDSC_STRICT_CHECK_" not in b_line:
                lines.append(f"            {b_line}")
        lines.append("            break;")
        lines.append("        }")

    lines.extend([
        "        default:",
        "            out = x;",
        "            break;",
        "    }",
        "",
        "    *state = s;",
        "    *aux   = a;",
        "    return out;",
        "}",
        "",
        "// NVRTC JIT 动态内核代码注入模板字符串 (消除手写 CUDA JIT 源码漂移)",
        "static const char* const SDSC_CUDA_DEVICE_OPS_SRC = R\"(",
        device_func_lines_str,
        ")\";",
        "",
        '#include "cuda_ops_vjp.cuh"',
        "",
        "#endif /* KUN_CELLULAR_CUDA_OPS_CUH_ */",
        ""
    ])
    return "\n".join(lines)

def generate_cuda_vjp_header(spec):
    prims = spec["sdsc_primitives"]
    device_vjp_lines = [
        "typedef struct {",
        "    float dx;",
        "    float ds_prev;",
        "    float da_prev;",
        "    float dg;",
        "} SdscCUDAVJP;",
        "",
        "SDSC_CUDA_DEVICE SdscCUDAVJP sdsc_cuda_vjp_primitive(",
        "    uint8_t op,",
        "    float g,",
        "    float x,",
        "    float s,",
        "    float a,",
        "    float out,",
        "    float s_next,",
        "    float a_next,",
        "    float dy,",
        "    float ds_next,",
        "    float da_next",
        ") {",
        "    SdscCUDAVJP ret;",
        "    float dx = 0.0f;",
        "    float ds_prev = 0.0f;",
        "    float da_prev = 0.0f;",
        "    float dg = 0.0f;",
        "",
        "    switch (op) {"
    ]

    for p in prims:
        device_vjp_lines.append(f"        case {p['id']}: {{ // {p['name']}")
        vjp_code = p.get("vjp_code", "").strip()
        for b_line in vjp_code.splitlines():
            device_vjp_lines.append(f"            {b_line}")
        device_vjp_lines.append("            break;")
        device_vjp_lines.append("        }")

    device_vjp_lines.extend([
        "        default:",
        "            dx = dy;",
        "            break;",
        "    }",
        "",
        "    ret.dx = dx;",
        "    ret.ds_prev = ds_prev;",
        "    ret.da_prev = da_prev;",
        "    ret.dg = dg;",
        "    return ret;",
        "}"
    ])
    device_vjp_lines_str = "\n".join(device_vjp_lines)

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_CUDA_OPS_VJP_CUH_",
        "#define KUN_CELLULAR_CUDA_OPS_VJP_CUH_",
        "",
        "#include <stdint.h>",
        "#include <math.h>",
        "",
        "#if defined(__CUDACC__) || defined(__CUDA_ARCH__)",
        "#define SDSC_CUDA_DEVICE __device__ __forceinline__",
        "#else",
        "#define SDSC_CUDA_DEVICE inline",
        "#endif",
        "",
        device_vjp_lines_str,
        "",
        "// NVRTC JIT 反向伴随 VJP 动态内核代码模板字符串",
        "static const char* const SDSC_CUDA_DEVICE_VJP_OPS_SRC = R\"(",
        device_vjp_lines_str,
        ")\";",
        "",
        "#endif /* KUN_CELLULAR_CUDA_OPS_VJP_CUH_ */",
        ""
    ]
    return "\n".join(lines)


def generate_cell_kernel_header(spec):
    """Generate the legacy-compatible and opt-in StrictCore cell kernel.

    The two public entry points only differ in normalization, validation, and
    initialization policy.  The actual CellType equations below are emitted
    once and selected by the shared step implementation.
    """
    prims = spec["sdsc_primitives"]
    cells = spec["cell_types"]
    primitive_ids = {primitive["name"]: primitive["id"] for primitive in prims}
    cells_by_kind = {}
    for cell in cells:
        cells_by_kind.setdefault(cell["legacy_kernel"]["kind"], []).append(cell)

    def c_float(value):
        rendered = f"{float(value):.17g}"
        if "." not in rendered and "e" not in rendered and "E" not in rendered:
            rendered += ".0"
        return rendered + "f"

    kind_constants = {
        "continuous": "SDSC_CELL_PARAMETER_CONTINUOUS",
        "channel_index": "SDSC_CELL_PARAMETER_CHANNEL_INDEX",
        "delay_ticks": "SDSC_CELL_PARAMETER_DELAY_TICKS",
        "enum": "SDSC_CELL_PARAMETER_MIN_MAX_MODE",
        "unused": "SDSC_CELL_PARAMETER_UNUSED",
    }

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_SDSC_CELL_KERNEL_H_",
        "#define KUN_CELLULAR_SDSC_CELL_KERNEL_H_",
        "",
        "#include <stdbool.h>",
        "#include <float.h>",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <limits.h>",
        "#include <math.h>",
        '#include "kun/cellular/sdsc_primitives.h"',
        "",
        "#if (defined(__GNUC__) || defined(__clang__)) && !defined(__STRICT_ANSI__)",
        "#define SDSC_CELL_KERNEL_INLINE static inline __attribute__((always_inline))",
        "#else",
        "#define SDSC_CELL_KERNEL_INLINE static inline",
        "#endif",
        "",
        "typedef enum {",
    ]
    for index, cell in enumerate(cells):
        comma = "," if index < len(cells) - 1 else ""
        lines.append(f"    SDSC_CELL_{cell['name']} = {cell['code']}{comma}")
    lines.extend([
        "} SdscCellTypeCode;",
        "",
        "typedef enum {",
        "    SDSC_CELL_KERNEL_OK = 0,",
        "    SDSC_CELL_KERNEL_INVALID_ARGUMENT = 1,",
        "    SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE = 2,",
        "    SDSC_CELL_KERNEL_INVALID_PARAMETER = 3,",
        "    SDSC_CELL_KERNEL_INVALID_PROFILE = 4,",
        "    SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND = 5,",
        "    SDSC_CELL_KERNEL_NONFINITE = 6,",
        "    SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE = 7,",
        "    SDSC_CELL_KERNEL_INVALID_STATE = 8,",
        "    SDSC_CELL_KERNEL_NUMERICAL_ERROR = 9,",
        "} SdscCellKernelStatus;",
        "",
        "typedef enum {",
        "    SDSC_CELL_KERNEL_PROFILE_LEGACY_COMPATIBLE = 0,",
        "    SDSC_CELL_KERNEL_PROFILE_STRICT_CORE = 1,",
        "} SdscCellKernelProfile;",
        "",
        "typedef enum {",
        "    SDSC_CELL_PARAMETER_CONTINUOUS = 0,",
        "    SDSC_CELL_PARAMETER_CHANNEL_INDEX = 1,",
        "    SDSC_CELL_PARAMETER_DELAY_TICKS = 2,",
        "    SDSC_CELL_PARAMETER_MIN_MAX_MODE = 3,",
        "    SDSC_CELL_PARAMETER_UNUSED = 4,",
        "} SdscCellKernelParameterKind;",
        "",
        "typedef struct {",
        "    SdscCellKernelParameterKind kind;",
        "    union {",
        "        double continuous;",
        "        size_t channel_index;",
        "        uint64_t delay_ticks;",
        "        uint8_t min_max_mode;",
        "    } value;",
        "} SdscCellKernelStrictParameter;",
        "",
        "typedef struct {",
        "    SdscCellKernelStrictParameter param1;",
        "    SdscCellKernelStrictParameter param2;",
        "} SdscCellKernelStrictParameters;",
        "",
        "SDSC_CELL_KERNEL_INLINE const char* sdsc_cell_kernel_status_string(",
        "    SdscCellKernelStatus status) {",
        "    switch (status) {",
        '        case SDSC_CELL_KERNEL_OK: return "ok";',
        '        case SDSC_CELL_KERNEL_INVALID_ARGUMENT: return "invalid argument";',
        '        case SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE: return "unknown cell type";',
        '        case SDSC_CELL_KERNEL_INVALID_PARAMETER: return "invalid parameter";',
        '        case SDSC_CELL_KERNEL_INVALID_PROFILE: return "invalid profile";',
        '        case SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND: return "invalid parameter kind";',
        '        case SDSC_CELL_KERNEL_NONFINITE: return "non-finite value";',
        '        case SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE: return "input out of range";',
        '        case SDSC_CELL_KERNEL_INVALID_STATE: return "invalid state";',
        '        case SDSC_CELL_KERNEL_NUMERICAL_ERROR: return "numerical error";',
        '        default: return "unknown kernel status";',
        "    }",
        "}",
        "",
        "typedef struct {",
        "    double* state_val;",
        "    double* aux_state;",
        "    double* prev_input;",
        "    double* output_val;",
        "    double* delay_buffer;",
        "    bool* latch_state;",
        "    uint8_t* delay_idx;",
        "    uint32_t activation_count;",
        "} SdscCellKernelStateView;",
        "",
        "/* Strict cell-kernel policy: finite consumed values, checked double-to-float",
        " * narrowing, checked intermediates before equation clamps, and finite",
        " * published state/output are required. Schema-defined clamps remain part",
        " * of the equation. activity_count is optional and is never read or changed",
        " * by strict execution; graph input-tensor validation is a later layer. */",
        "typedef struct {",
        "    double* state_val;",
        "    double* aux_state;",
        "    double* prev_input;",
        "    double* output_val;",
        "    double* delay_buffer;",
        "    bool* latch_state;",
        "    uint8_t* delay_idx;",
        "    bool* initialized;",
        "    const uint32_t* activity_count;",
        "} SdscCellKernelStrictStateView;",
        "",
        "typedef struct {",
        "    float state_min;",
        "    float state_max;",
        "    float out_min;",
        "    float out_max;",
        "} SdscCellKernelBounds;",
        "",
        "typedef struct {",
        "    double param1;",
        "    double param2;",
        "    size_t channel;",
        "    int delay_ticks;",
        "} SdscCellKernelNormalizedParameters;",
        "",
        "SDSC_CELL_KERNEL_INLINE bool sdsc_cell_type_is_valid(uint8_t cell_type) {",
        "    switch (cell_type) {",
    ])
    for cell in cells:
        lines.append(f"        case SDSC_CELL_{cell['name']}:")
    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE uint8_t sdsc_cell_type_to_legacy_eval_op(uint8_t cell_type) {",
        "    switch (cell_type) {",
    ])
    for cell in cells:
        lines.append(
            f"        case SDSC_CELL_{cell['name']}: return {primitive_ids[cell['legacy_eval_op']]};"
        )
    lines.extend([
        "        default: return 26;",
        "    }",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelBounds sdsc_cell_kernel_bounds(uint8_t op) {",
        "    switch (op) {",
    ])
    for primitive in prims:
        bounds = primitive.get("bounds", {})
        state_bounds = bounds.get("state", [-1e9, 1e9])
        out_bounds = bounds.get("out", [-1e9, 1e9])
        lines.extend([
            f"        case {primitive['id']}: {{",
            "            SdscCellKernelBounds result = {"
            f"{c_float(state_bounds[0])}, {c_float(state_bounds[1])}, "
            f"{c_float(out_bounds[0])}, {c_float(out_bounds[1])}" + "};",
            "            return result;",
            "        }",
        ])
    lines.extend([
        "        default: {",
        "            SdscCellKernelBounds result = {-1000000000.0f, 1000000000.0f,",
        "                -1000000000.0f, 1000000000.0f};",
        "            return result;",
        "        }",
        "    }",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE double sdsc_cell_kernel_clamp_double(",
        "    double value, double lower, double upper) {",
        "    return value < lower ? lower : (value > upper ? upper : value);",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE float sdsc_cell_kernel_clamp_float(",
        "    float value, float lower, float upper) {",
        "    return value < lower ? lower : (value > upper ? upper : value);",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE bool sdsc_cell_kernel_normalize_delay(",
        "    double param1, int* delay_ticks) {",
        "    if (delay_ticks == NULL) return false;",
        "    const double scaled_delay = param1 * 16.0;",
        "    const double floored_delay = floor(scaled_delay);",
        "    if (!isfinite(scaled_delay) || floored_delay < (double)INT_MIN ||",
        "        floored_delay > (double)INT_MAX) {",
        "        return false;",
        "    }",
        "    int normalized = (int)floored_delay;",
        "    if (normalized < 1) normalized = 1;",
        "    if (normalized > 16) normalized = 16;",
        "    *delay_ticks = normalized;",
        "    return true;",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE bool sdsc_cell_kernel_strict_double_to_float(",
        "    double value, float* narrowed) {",
        "    if (narrowed == NULL || !isfinite(value) ||",
        "        value < -(double)FLT_MAX || value > (double)FLT_MAX)",
        "        return false;",
        "    *narrowed = (float)value;",
        "    return isfinite(*narrowed);",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE bool sdsc_cell_kernel_strict_finite_state(",
        "    const SdscCellKernelStateView* state) {",
        "    if (!isfinite(*state->state_val) || !isfinite(*state->aux_state) ||",
        "        !isfinite(*state->prev_input) || !isfinite(*state->output_val) ||",
        "        *state->delay_idx >= 16u) return false;",
        "    for (size_t i = 0; i < 16u; ++i) {",
        "        if (!isfinite(state->delay_buffer[i])) return false;",
        "    }",
        "    return true;",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus",
        "sdsc_cell_kernel_strict_parameter_kinds(",
        "    uint8_t cell_type, const SdscCellKernelStrictParameters* parameters) {",
        "    if (parameters == NULL) return SDSC_CELL_KERNEL_INVALID_ARGUMENT;",
        "    switch (cell_type) {",
    ])
    for cell in cells:
        lines.append(f"        case SDSC_CELL_{cell['name']}:")
        lines.append("            if (")
        for slot_index, parameter in enumerate(cell["contract"]["parameters"]):
            slot = "param1" if parameter["slot"] == "param1" else "param2"
            connector = "                " if slot_index == 0 else " || "
            lines.append(
                f"{connector}parameters->{slot}.kind != {kind_constants[parameter['kind']]}"
            )
        lines.extend([
            "            ) return SDSC_CELL_KERNEL_INVALID_PARAMETER_KIND;",
            "            break;",
        ])
    lines.extend([
        "        default:",
        "            return SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;",
        "    }",
        "    return SDSC_CELL_KERNEL_OK;",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus",
        "sdsc_cell_kernel_normalize_strict_parameters(",
        "    uint8_t cell_type, const SdscCellKernelStrictParameters* parameters,",
        "    SdscCellKernelNormalizedParameters* normalized) {",
        "    if (parameters == NULL || normalized == NULL) return SDSC_CELL_KERNEL_INVALID_ARGUMENT;",
        "    normalized->param1 = 1.0;",
        "    normalized->param2 = 0.0;",
        "    normalized->channel = 0u;",
        "    normalized->delay_ticks = 0;",
        "    const SdscCellKernelStatus kind_status =",
        "        sdsc_cell_kernel_strict_parameter_kinds(cell_type, parameters);",
        "    if (kind_status != SDSC_CELL_KERNEL_OK) return kind_status;",
        "    switch (cell_type) {",
    ])
    for cell in cells:
        lines.append(f"        case SDSC_CELL_{cell['name']}: {{")
        for parameter in cell["contract"]["parameters"]:
            slot = parameter["slot"]
            if parameter["kind"] == "continuous":
                lines.append(
                    f"            normalized->{slot} = parameters->{slot}.value.continuous;"
                )
            elif parameter["kind"] == "channel_index":
                lines.append(
                    f"            normalized->channel = parameters->{slot}.value.channel_index;"
                )
            elif parameter["kind"] == "delay_ticks":
                lines.extend([
                    f"            if (parameters->{slot}.value.delay_ticks < 1u ||",
                    f"                parameters->{slot}.value.delay_ticks > 16u)",
                    "                return SDSC_CELL_KERNEL_INVALID_PARAMETER;",
                    f"            normalized->delay_ticks = (int)parameters->{slot}.value.delay_ticks;",
                ])
            elif parameter["kind"] == "enum":
                lines.extend([
                    f"            if (parameters->{slot}.value.min_max_mode > 1u)",
                    "                return SDSC_CELL_KERNEL_INVALID_PARAMETER;",
                    f"            normalized->{slot} = parameters->{slot}.value.min_max_mode ? 1.0 : 0.0;",
                ])
        lines.append("            break;")
        lines.append("        }")
    lines.extend([
        "        default:",
        "            return SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;",
        "    }",
        "    if (!isfinite(normalized->param1) || !isfinite(normalized->param2))",
        "        return SDSC_CELL_KERNEL_INVALID_PARAMETER;",
        "    return SDSC_CELL_KERNEL_OK;",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step_common(",
        "    uint8_t cell_type, const SdscCellKernelNormalizedParameters* parameters,",
        "    double in0, double in1, size_t in_dim, const double* inputs,",
        "    SdscCellKernelStateView* state, bool strict, bool* initialized) {",
        "    double next_state = *state->state_val;",
        "    double next_aux = *state->aux_state;",
        "    double next_previous = *state->prev_input;",
        "    double next_output = *state->output_val;",
        "    double next_delay[16];",
        "    for (size_t i = 0; i < 16u; ++i) next_delay[i] = state->delay_buffer[i];",
        "    bool next_latch = *state->latch_state;",
        "    uint8_t next_delay_index = *state->delay_idx;",
        "    if (strict) {",
        "        if (initialized == NULL || !sdsc_cell_kernel_strict_finite_state(state))",
        "            return initialized == NULL ? SDSC_CELL_KERNEL_INVALID_ARGUMENT :",
        "                SDSC_CELL_KERNEL_INVALID_STATE;",
        "        if (cell_type != SDSC_CELL_SENSE_RAW_INPUT_0 &&",
        "            cell_type != SDSC_CELL_SENSE_RAW_INPUT_1 &&",
        "            cell_type != SDSC_CELL_SENSE_RAW_INPUT_2 &&",
        "            cell_type != SDSC_CELL_SENSE_RAW_INPUT_3 &&",
        "            cell_type != SDSC_CELL_SENSE_CHANNEL && !isfinite(in0))",
        "            return SDSC_CELL_KERNEL_NONFINITE;",
        "        if ((cell_type == SDSC_CELL_OP_SUM || cell_type == SDSC_CELL_OP_SUB ||",
        "             cell_type == SDSC_CELL_OP_MULTIPLY || cell_type == SDSC_CELL_OP_QUADRATIC ||",
        "             cell_type == SDSC_CELL_GATE_MIN_MAX) && !isfinite(in1))",
        "            return SDSC_CELL_KERNEL_NONFINITE;",
        "    }",
        "",
    ])
    for cell in cells_by_kind.get("receptor_fixed", []):
        channel = cell["legacy_kernel"]["channel"]
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            f"        if (strict && (inputs == NULL || in_dim <= {channel}))",
            "            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;",
            "        if (!strict) {",
            f"            next_output = (in_dim > {channel} && inputs) ?",
            f"                inputs[{channel}] * parameters->param1 : 0.0;",
            "        } else {",
            f"            const double source = inputs[{channel}];",
            "            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;",
            "            next_output = source * parameters->param1;",
            "        }",
            "        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    lines.extend([
        "    if (cell_type == SDSC_CELL_SENSE_CHANNEL) {",
        "        if (strict && (inputs == NULL || parameters->channel >= in_dim))",
        "            return SDSC_CELL_KERNEL_INPUT_OUT_OF_RANGE;",
        "        if (!strict) {",
        "            next_output = (parameters->channel < in_dim && inputs) ?",
        "                inputs[parameters->channel] * parameters->param1 : 0.0;",
        "        } else {",
        "            const double source = inputs[parameters->channel];",
        "            if (!isfinite(source)) return SDSC_CELL_KERNEL_NONFINITE;",
        "            next_output = source * parameters->param1;",
        "        }",
        "        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        goto sdsc_cell_kernel_commit;",
        "    }",
        "",
    ])
    if cells_by_kind.get("delay"):
        lines.extend([
            "    if (cell_type == SDSC_CELL_OP_DELAY_N) {",
            "        const size_t read_idx = ((size_t)next_delay_index + 16u -",
            "            (size_t)parameters->delay_ticks) & 15u;",
            "        next_output = next_delay[read_idx];",
            "        next_delay[next_delay_index & 15u] = in0;",
            "        next_delay_index = (uint8_t)((next_delay_index + 1u) & 15u);",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    passthrough_names = [
        f"SDSC_CELL_{cell['name']}" for cell in cells_by_kind.get("passthrough", [])
    ]
    if passthrough_names:
        lines.extend([
            "    if (" + " || ".join(f"cell_type == {name}" for name in passthrough_names) + ") {",
            "        next_output = in0;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("quadratic", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        next_output = parameters->param1 * in0 * in0 +",
            "            parameters->param2 * in0 * in1;",
            "        if (strict && !isfinite(next_output)) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("hysteresis", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        if (in0 > parameters->param1) next_latch = true;",
            "        else if (in0 < parameters->param2) next_latch = false;",
            "        next_output = next_latch ? 1.0 : -1.0;",
            "        next_state = next_output;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("threshold", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        next_output = (in0 > parameters->param1) ? 1.0 : 0.0;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("deadzone", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        next_output = (fabs(in0) > fabs(parameters->param1)) ? in0 : 0.0;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("minmax", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        next_output = (parameters->param1 > 0.5) ?",
            "            (in0 < in1 ? in1 : in0) : (in1 < in0 ? in1 : in0);",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("ema", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        if (!strict) {",
            "            if (!isfinite(in0)) in0 = 0.0;",
            "            if (!isfinite(next_state)) next_state = 0.0;",
            "        }",
            "        const double alpha = sdsc_cell_kernel_clamp_double(",
            "            parameters->param1, 0.001, 1.0);",
            "        if (strict && !*initialized) next_state = in0;",
            "        else if (!strict && state->activation_count == 0) next_state = in0;",
            "        else next_state = alpha * in0 + (1.0 - alpha) * next_state;",
            "        next_output = next_state;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("diff", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        next_output = in0 - next_previous;",
            "        next_previous = in0;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    for cell in cells_by_kind.get("oscillator", []):
        lines.extend([
            f"    if (cell_type == SDSC_CELL_{cell['name']}) {{",
            "        if ((!strict && state->activation_count == 0 && fabs(next_state) < 1e-6 &&",
            "             fabs(next_aux) < 1e-6) ||",
            "            (strict && !*initialized && fabs(next_state) < 1e-6 &&",
            "             fabs(next_aux) < 1e-6)) next_state = 0.1;",
            "        const double mu = (fabs(parameters->param1) > 1e-4) ?",
            "            sdsc_cell_kernel_clamp_double(fabs(parameters->param1), 0.01, 5.0) : 1.0;",
            "        const double dt = (fabs(parameters->param2) > 1e-4) ?",
            "            sdsc_cell_kernel_clamp_double(fabs(parameters->param2), 0.001, 0.2) : 0.05;",
            "        const double ds1 = next_aux;",
            "        const double ds2 = mu * (1.0 - next_state * next_state) * next_aux -",
            "            next_state + in0;",
            "        const double raw_next_state = next_state + ds1 * dt;",
            "        const double raw_next_aux = next_aux + ds2 * dt;",
            "        if (strict && (!isfinite(ds1) || !isfinite(ds2) ||",
            "            !isfinite(raw_next_state) || !isfinite(raw_next_aux)))",
            "            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
            "        next_state = sdsc_cell_kernel_clamp_double(raw_next_state, -10.0, 10.0);",
            "        next_aux = sdsc_cell_kernel_clamp_double(raw_next_aux, -10.0, 10.0);",
            "        next_output = next_state;",
            "        if (strict && (!isfinite(next_state) || !isfinite(next_aux) ||",
            "            !isfinite(next_output))) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
            "        goto sdsc_cell_kernel_commit;",
            "    }",
            "",
        ])
    lines.extend([
        "    {",
        "        const uint8_t op = sdsc_cell_type_to_legacy_eval_op(cell_type);",
        "        float s = 0.0f;",
        "        float a = 0.0f;",
        "        float g = 0.0f;",
        "        float x = 0.0f;",
        "        bool folded_input = false;",
        "        if (!strict) {",
        "            s = (float)next_state;",
        "            a = (float)next_aux;",
        "            g = (float)parameters->param1;",
        "            x = (float)in0;",
        "            if (!isfinite(s)) s = 0.0f;",
        "            if (!isfinite(a)) a = 0.0f;",
        "            if (!isfinite(g)) g = 1.0f;",
        "            if (!isfinite(x)) x = 0.0f;",
        "        } else {",
        "            if (!sdsc_cell_kernel_strict_double_to_float(next_state, &s) ||",
        "                !sdsc_cell_kernel_strict_double_to_float(next_aux, &a) ||",
        "                !sdsc_cell_kernel_strict_double_to_float(parameters->param1, &g))",
        "                return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        }",
    ])
    for kind, expression in (
        ("default_sum", "in0 + in1"),
        ("default_sub", "in0 - in1"),
        ("default_multiply", "in0 * in1"),
    ):
        for cell in cells_by_kind.get(kind, []):
            lines.extend([
                f"        if (cell_type == SDSC_CELL_{cell['name']}) {{",
                f"            const double folded = {expression};",
                "            folded_input = true;",
                "            if (strict) {",
                "                if (!sdsc_cell_kernel_strict_double_to_float(folded, &x))",
                "                    return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
                "            } else {",
                "                x = (float)folded;",
                "            }",
                "        }",
            ])
    lines.extend([
        "        if (strict && !folded_input &&",
        "            !sdsc_cell_kernel_strict_double_to_float(in0, &x))",
        "            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        if (!strict && !isfinite(x)) x = 0.0f;",
        "        bool primitive_valid = true;",
        "        float out = sdsc_primitive_eval_profile(op, g, x, &s, &a,",
        "            strict, &primitive_valid);",
        "        if (strict && !primitive_valid)",
        "            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        if (!strict) {",
        "            if (!isfinite(s)) s = 0.0f;",
        "            if (!isfinite(out)) out = 0.0f;",
        "        } else if (!isfinite(s) || !isfinite(a) || !isfinite(out)) {",
        "            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        }",
        "        const SdscCellKernelBounds bounds = sdsc_cell_kernel_bounds(op);",
        "        s = sdsc_cell_kernel_clamp_float(s, bounds.state_min, bounds.state_max);",
        "        out = sdsc_cell_kernel_clamp_float(out, bounds.out_min, bounds.out_max);",
        "        if (strict && (!isfinite(s) || !isfinite(a) || !isfinite(out)))",
        "            return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        next_state = (double)s;",
        "        next_aux = (double)a;",
        "        next_output = (double)out;",
        "    }",
        "",
        "sdsc_cell_kernel_commit:",
        "    if (strict && (!isfinite(next_state) || !isfinite(next_aux) ||",
        "        !isfinite(next_previous) || !isfinite(next_output) || next_delay_index >= 16u))",
        "        return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "    if (strict) {",
        "        for (size_t i = 0; i < 16u; ++i) {",
        "            if (!isfinite(next_delay[i])) return SDSC_CELL_KERNEL_NUMERICAL_ERROR;",
        "        }",
        "    }",
        "    *state->state_val = next_state;",
        "    *state->aux_state = next_aux;",
        "    *state->prev_input = next_previous;",
        "    *state->output_val = next_output;",
        "    for (size_t i = 0; i < 16u; ++i) state->delay_buffer[i] = next_delay[i];",
        "    *state->latch_state = next_latch;",
        "    *state->delay_idx = next_delay_index;",
        "    if (strict) *initialized = true;",
        "    return SDSC_CELL_KERNEL_OK;",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step_profile(",
        "    SdscCellKernelProfile profile, uint8_t cell_type,",
        "    SdscCellKernelStrictParameters parameters, double in0, double in1,",
        "    size_t in_dim, const double* inputs,",
        "    SdscCellKernelStrictStateView* strict_state) {",
        "    if (profile != SDSC_CELL_KERNEL_PROFILE_STRICT_CORE)",
        "        return SDSC_CELL_KERNEL_INVALID_PROFILE;",
        "    if (!sdsc_cell_type_is_valid(cell_type) || strict_state == NULL ||",
        "        strict_state->state_val == NULL || strict_state->aux_state == NULL ||",
        "        strict_state->prev_input == NULL || strict_state->output_val == NULL ||",
        "        strict_state->delay_buffer == NULL || strict_state->latch_state == NULL ||",
        "        strict_state->delay_idx == NULL || strict_state->initialized == NULL)",
        "        return sdsc_cell_type_is_valid(cell_type) ? SDSC_CELL_KERNEL_INVALID_ARGUMENT :",
        "            SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;",
        "    SdscCellKernelNormalizedParameters normalized;",
        "    const SdscCellKernelStatus normalized_status =",
        "        sdsc_cell_kernel_normalize_strict_parameters(cell_type, &parameters, &normalized);",
        "    if (normalized_status != SDSC_CELL_KERNEL_OK) return normalized_status;",
        "    SdscCellKernelStateView base = {",
        "        strict_state->state_val, strict_state->aux_state, strict_state->prev_input,",
        "        strict_state->output_val, strict_state->delay_buffer, strict_state->latch_state,",
        "        strict_state->delay_idx, 0u};",
        "    return sdsc_cell_kernel_step_common(cell_type, &normalized, in0, in1,",
        "        in_dim, inputs, &base, true, strict_state->initialized);",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step_strict(",
        "    uint8_t cell_type, const SdscCellKernelStrictParameters* parameters,",
        "    double in0, double in1, size_t in_dim, const double* inputs,",
        "    SdscCellKernelStrictStateView* strict_state) {",
        "    if (parameters == NULL) return SDSC_CELL_KERNEL_INVALID_ARGUMENT;",
        "    return sdsc_cell_kernel_step_profile(",
        "        SDSC_CELL_KERNEL_PROFILE_STRICT_CORE, cell_type, *parameters,",
        "        in0, in1, in_dim, inputs, strict_state);",
        "}",
        "",
        "SDSC_CELL_KERNEL_INLINE SdscCellKernelStatus sdsc_cell_kernel_step(",
        "    uint8_t cell_type, double param1, double param2, double in0, double in1,",
        "    size_t in_dim, const double* inputs, SdscCellKernelStateView* state) {",
        "    if (!sdsc_cell_type_is_valid(cell_type)) return SDSC_CELL_KERNEL_UNKNOWN_CELL_TYPE;",
        "    if (state == NULL || state->state_val == NULL || state->aux_state == NULL ||",
        "        state->prev_input == NULL || state->output_val == NULL ||",
        "        state->delay_buffer == NULL || state->latch_state == NULL || state->delay_idx == NULL)",
        "        return SDSC_CELL_KERNEL_INVALID_ARGUMENT;",
        "    SdscCellKernelNormalizedParameters normalized = {param1, param2, 0u, 0};",
        "    if (cell_type == SDSC_CELL_SENSE_CHANNEL && param2 >= 0.0) {",
        "        if (!isfinite(param2) || floor(param2) >= ldexp(1.0,",
        "            (int)(sizeof(size_t) * CHAR_BIT))) return SDSC_CELL_KERNEL_INVALID_PARAMETER;",
        "        normalized.channel = (size_t)floor(param2);",
        "    }",
        "    if (cell_type == SDSC_CELL_OP_DELAY_N &&",
        "        !sdsc_cell_kernel_normalize_delay(param1, &normalized.delay_ticks))",
        "        return SDSC_CELL_KERNEL_INVALID_PARAMETER;",
        "    return sdsc_cell_kernel_step_common(cell_type, &normalized, in0, in1,",
        "        in_dim, inputs, state, false, NULL);",
        "}",
        "",
        "#undef SDSC_CELL_KERNEL_INLINE",
        "",
        "#endif /* KUN_CELLULAR_SDSC_CELL_KERNEL_H_ */",
        "",
    ])
    return "\n".join(lines)


def generate_cpp_header(spec):
    prims = spec["sdsc_primitives"]
    cells = spec["cell_types"]

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_GENERATED_OPS_HPP_",
        "#define KUN_CELLULAR_GENERATED_OPS_HPP_",
        "",
        "#include <cstdint>",
        "#include <string>",
        "#include <string_view>",
        "#include <array>",
        "#include <algorithm>",
        "#include <cmath>",
        "#include <stdexcept>",
        "#include \"kun/cellular/sdsc_primitives.h\"",
        "#include \"kun/cellular/sdsc_cell_kernel.h\"",
        "",
        "namespace kun {",
        "",
        "// ============================================================================",
        "// 1. 软件定义硅基细胞计算机 (SDSCC) 硬件原子原语枚举",
        "// ============================================================================",
        "enum class SdscOpType : uint8_t {"
    ]

    for i, p in enumerate(prims):
        sep = "," if i < len(prims) - 1 else ""
        lines.append(f"    {p['name']} = {p['id']}{sep}")

    lines.extend([
        "};",
        "",
        "// ============================================================================",
        "// 2. 形态学细胞类型 (CellType): 生物计算原语完整枚举",
        "// ============================================================================",
        "enum class CellType : uint8_t {"
    ])

    for i, c in enumerate(cells):
        sep = "," if i < len(cells) - 1 else ""
        lines.append(f"    {c['name']:<24} = {c['code']}{sep}   // {c['description']}")

    lines.extend([
        "};",
        "",
        "// ============================================================================",
        "// 3. 字符串名称双向转换与形态学元数据反射",
        "// ============================================================================",
        "inline const char* to_string(CellType t) {",
        "    switch (t) {"
    ])

    for c in cells:
        lines.append(f"        case CellType::{c['name']}: return \"{c['str_name']}\";")

    lines.extend([
        "        default: return \"Cell_Unknown\";",
        "    }",
        "}",
        "",
        "inline CellType cell_type_from_string(std::string_view name) {"
    ])

    for c in cells:
        lines.append(f"    if (name == \"{c['str_name']}\") return CellType::{c['name']};")

    lines.extend([
        "    return CellType::OP_EMA;",
        "}",
        "",
        "inline bool is_receptor_cell(CellType t) {",
        "    switch (t) {"
    ])

    for c in cells:
        if c["category"] == "RECEPTOR":
            lines.append(f"        case CellType::{c['name']}:")

    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        "",
        "inline bool is_effector_cell(CellType t) {",
        "    switch (t) {"
    ])

    for c in cells:
        if c["category"] == "EFFECTOR":
            lines.append(f"        case CellType::{c['name']}:")

    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        "",
        "inline bool is_valid_cell_type_code(uint8_t op) {",
        "    switch (static_cast<CellType>(op)) {"
    ])

    for c in cells:
        lines.append(f"        case CellType::{c['name']}:")

    lines.extend([
        "            return true;",
        "        default:",
        "            return false;",
        "    }",
        "}",
        ""
    ])

    lines.extend([
        "inline uint8_t cell_type_to_sdsc_opcode(CellType t) {",
        "    switch (t) {",
    ])
    primitive_ids = {primitive["name"]: primitive["id"] for primitive in prims}
    for cell in cells:
        lines.append(
            f"        case CellType::{cell['name']}: return {primitive_ids[cell['legacy_eval_op']]};"
        )
    lines.extend([
        "        default: return 26; // SDSC_OP_PASSTHRU",
        "    }",
        "}",
        "",
        "inline uint8_t cell_type_to_serialization_code(CellType t) {",
        "    return static_cast<uint8_t>(t);",
        "}",
        "",
        "inline CellType serialization_code_to_cell_type(uint8_t code) {",
        "    return static_cast<CellType>(code);",
        "}",
        "",
        "inline CellType sdsc_opcode_to_cell_type(uint8_t op, uint8_t flags = 0, uint32_t version = 3) {",
        "    if (version >= 3) {",
        "        if (is_valid_cell_type_code(op)) {",
        "            return static_cast<CellType>(op);",
        "        }",
        "    }",
        "    if (flags & 0x01) {",
        "        if (op == 0) return CellType::SENSE_RAW_INPUT_0;",
        "        if (op == 1) return CellType::SENSE_RAW_INPUT_1;",
        "        if (op == 2) return CellType::SENSE_RAW_INPUT_2;",
        "        if (op == 3) return CellType::SENSE_RAW_INPUT_3;",
        "        return CellType::SENSE_CHANNEL;",
        "    }",
        "    if (flags & 0x02) {",
        "        if (op == 21) return CellType::ACT_PRIMARY_POSITIVE;",
        "        if (op == 22) return CellType::ACT_PRIMARY_NEGATIVE;",
        "        if (op == 23) return CellType::ACT_DEFENSIVE_RESET;",
        "        return CellType::ACT_CHANNEL;",
        "    }",
        "    switch (op) {"
    ])
    legacy_map = {
        0: "SENSE_RAW_INPUT_0", 1: "SENSE_RAW_INPUT_1", 2: "SENSE_RAW_INPUT_2", 3: "SENSE_RAW_INPUT_3",
        4: "OP_SUM", 5: "OP_INTEGRAL", 8: "OP_EMA", 10: "OP_ABS", 11: "OP_MULTIPLY", 12: "OP_DIFF",
        13: "OP_SUB", 14: "OP_RATIO", 15: "GATE_THRESHOLD", 16: "GATE_HYSTERESIS", 17: "GATE_DEADZONE",
        18: "GATE_INHIBIT", 19: "GATE_AND", 20: "GATE_MIN_MAX",
        21: "ACT_PRIMARY_POSITIVE", 22: "ACT_PRIMARY_NEGATIVE", 23: "ACT_DEFENSIVE_RESET",
        24: "ASSOCIATION_HUB", 25: "OP_OSCILLATOR"
    }
    for op_val, cell_name in legacy_map.items():
        lines.append(f"        case {op_val}: return CellType::{cell_name};")
    lines.extend([
        "        default: return CellType::OP_EMA;",
        "    }",
        "}",
        "",
        "inline uint8_t cell_type_to_sdsc_eval_op(CellType t) {",
        "    return cell_type_to_sdsc_opcode(t);",
        "}",
        "",
        "// 硬件原语数值界与形式化证书约束",
        "struct PrimitiveBounds {",
        "    float state_min;",
        "    float state_max;",
        "    float out_min;",
        "    float out_max;",
        "    float param_g_min;",
        "    float param_g_max;",
        "};",
        "",
        "// 硬件原语静态反射元数据 (含可微性与直通梯度模式)",
        "struct PrimitiveMeta {",
        "    uint8_t id;",
        "    const char* name;",
        "    const char* category;",
        "    bool has_state;",
        "    bool has_aux;",
        "    float default_p1;",
        "    float default_p2;",
        "    const char* lyapunov_bound;",
        "    bool differentiable;",
        "    const char* ste_gradient;",
        "    PrimitiveBounds bounds;",
        "};",
        "",
        f"inline constexpr std::array<PrimitiveMeta, {len(prims)}> SDSC_PRIMITIVES_META = {{{{",
    ])

    for p in prims:
        has_s = "true" if p['has_state'] else "false"
        has_a = "true" if p['has_aux'] else "false"
        diff = "true" if p.get('differentiable', True) else "false"
        ste = p.get('ste_gradient', 'none')
        bounds = p.get('bounds', {})
        s_b = bounds.get('state', [-1e9, 1e9])
        o_b = bounds.get('out', [-1e9, 1e9])
        g_b = bounds.get('params', {}).get('g', [0.0, 4.0])
        b_str = f"{{{s_b[0]}f, {s_b[1]}f, {o_b[0]}f, {o_b[1]}f, {g_b[0]}f, {g_b[1]}f}}"
        lines.append(f'    {{{p["id"]}, "{p["name"]}", "{p["category"]}", {has_s}, {has_a}, {p["default_p1"]}f, {p["default_p2"]}f, "{p["lyapunov_bound"]}", {diff}, "{ste}", {b_str}}},')

    lines.extend([
        "}};",
        "",
        "inline constexpr bool is_primitive_differentiable(uint8_t op) {",
        "    if (op < SDSC_PRIMITIVES_META.size()) {",
        "        return SDSC_PRIMITIVES_META[op].differentiable;",
        "    }",
        "    return true;",
        "}",
        "",
        "inline constexpr const char* get_primitive_ste(uint8_t op) {",
        "    if (op < SDSC_PRIMITIVES_META.size()) {",
        "        return SDSC_PRIMITIVES_META[op].ste_gradient;",
        "    }",
        "    return \"none\";",
        "}",
        "",
        "inline constexpr PrimitiveBounds get_primitive_bounds(uint8_t op) {",
        "    if (op < SDSC_PRIMITIVES_META.size()) {",
        "        return SDSC_PRIMITIVES_META[op].bounds;",
        "    }",
        "    return {-1e9f, 1e9f, -1e9f, 1e9f, 0.0f, 4.0f};",
        "}",
        "",
        "// C11 LEGACY kernel adapter; all CellType arithmetic lives in sdsc_cell_kernel.h",
        "template<typename CellT>",
        "inline void dispatch_cell_forward(",
        "    CellT& c, double in0, double in1, size_t in_dim, const double* inputs)",
        "{",
        "    SdscCellKernelStateView state{",
        "        &c.state_val, &c.aux_state, &c.prev_input, &c.output_val,",
        "        c.delay_buffer, &c.latch_state, &c.delay_idx, c.activation_count};",
        "    const auto status = sdsc_cell_kernel_step(",
        "        static_cast<uint8_t>(c.type), c.param1, c.param2, in0, in1,",
        "        in_dim, inputs, &state);",
        "    if (status != SDSC_CELL_KERNEL_OK) {",
        "        throw std::invalid_argument(",
        "            std::string(\"legacy cell kernel dispatch failed: \") +",
        "            sdsc_cell_kernel_status_string(status));",
        "    }",
        "}",
        "",
        "} // namespace kun",
        "",
        "#endif /* KUN_CELLULAR_GENERATED_OPS_HPP_ */",
        ""
    ])
    return "\n".join(lines)


def _cpp_string(value):
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _cpp_float(value):
    return f"{float(value):.17g}"


def generate_contract_header(spec):
    cells = spec["cell_types"]
    kind_enum = {
        "continuous": "ParameterKind::Continuous",
        "channel_index": "ParameterKind::ChannelIndex",
        "delay_ticks": "ParameterKind::DelayTicks",
        "enum": "ParameterKind::Enum",
        "unused": "ParameterKind::Unused",
    }
    value_type_enum = {
        "Continuous": "ParameterValueType::Continuous",
        "ChannelIndex": "ParameterValueType::ChannelIndex",
        "DelayTicks": "ParameterValueType::DelayTicks",
        "MinMaxMode": "ParameterValueType::MinMaxMode",
        "Unused": "ParameterValueType::Unused",
    }
    state_enum = {
        "state_val": "StateField::StateValue",
        "aux_state": "StateField::AuxState",
        "previous_input": "StateField::PreviousInput",
        "delay_buffer": "StateField::DelayBuffer",
        "delay_index": "StateField::DelayIndex",
        "latch_state": "StateField::LatchState",
    }
    initialization_enum = {
        "none": "InitializationDependency::None",
        "state_zero": "InitializationDependency::StateValue",
        "activity_count": "InitializationDependency::ActivityCount",
    }
    vjp_enum = {
        "exact": "VjpCapability::Exact",
        "approximate_or_ste": "VjpCapability::ApproximateOrSTE",
        "unsupported": "VjpCapability::Unsupported",
    }
    execution_policy_enum = {
        "default_leaf": "ExecutionPolicy::DefaultLeaf",
        "special_double": "ExecutionPolicy::SpecialDouble",
        "generic_passthrough": "ExecutionPolicy::GenericPassthrough",
    }
    reset_enum = {
        "unused": "ResetAction::Unused",
        "zero": "ResetAction::Zero",
        "false": "ResetAction::FalseValue",
    }

    lines = [
        AUTO_GEN_BANNER,
        "#ifndef KUN_CELLULAR_CORE_PRIMITIVE_CONTRACT_HPP_",
        "#define KUN_CELLULAR_CORE_PRIMITIVE_CONTRACT_HPP_",
        "",
        "#include <array>",
        "#include <cmath>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <functional>",
        "#include <optional>",
        "#include <span>",
        "#include <type_traits>",
        "#include <variant>",
        '#include "kun/cellular/core/semantic_profile.hpp"',
        '#include "kun/cellular/generated_ops.hpp"',
        "",
        "namespace kun::core {",
        "",
        "enum class ParameterSlot : uint8_t { Param1 = 0, Param2 = 1 };",
        "enum class ParameterKind : uint8_t { Continuous, ChannelIndex, DelayTicks, Enum, Unused };",
        "enum class ParameterValueType : uint8_t { Continuous, ChannelIndex, DelayTicks, MinMaxMode, Unused };",
        "enum class StateField : uint8_t { StateValue, AuxState, PreviousInput, DelayBuffer, DelayIndex, LatchState };",
        "enum class InitializationDependency : uint8_t { None, StateValue, ActivityCount };",
        "enum class VjpCapability : uint8_t { Exact, ApproximateOrSTE, Unsupported };",
        "enum class ExecutionPolicy : uint8_t {",
        "    DefaultLeaf,        // float conversion, finite sanitize, mapped primitive, PrimitiveBounds post-clamp",
        "    SpecialDouble,      // legacy double branch with branch-local transforms; no generic leaf post-clamp",
        "    GenericPassthrough, // legacy double in0 pass-through; no gain or primitive clamp",
        "};",
        "enum class ResetAction : uint8_t { Unused, Zero, FalseValue };",
        "enum class StrictExecutionStatus : uint8_t {",
        "    Unsupported,  // no native strict cell-kernel execution",
        "    Implemented,  // strict shared cell kernel only; graph executors remain separate",
        "};",
        "",
        "struct ResetMetadata {",
        "    ResetAction state_value;",
        "    ResetAction aux_state;",
        "    ResetAction previous_input;",
        "    ResetAction delay_buffer;",
        "    ResetAction delay_index;",
        "    ResetAction latch_state;",
        "    ResetAction activation_count;",
        "    ResetAction output_value;",
        "};",
        "",
        "struct ParameterDescriptor {",
        "    const char* name;",
        "    ParameterSlot slot;",
        "    ParameterKind kind;",
        "    ParameterValueType value_type;",
        "    const char* legacy_mapping;",
        "    double search_min;",
        "    double search_max;",
        "    bool has_search_domain;",
        "    bool finite_only;",
        "    bool trainable_continuous;",
        "};",
        "",
        "struct CellContract {",
        "    CellType type;",
        "    uint8_t code;",
        "    const char* name;",
        "    uint8_t input_port_count;",
        "    const char* input_semantics;",
        "    const char* output_contract;",
        "    uint8_t mapped_opcode;",
        "    PrimitiveBounds mapped_bounds;",
        "    ExecutionPolicy execution_policy;",
        "    std::array<ParameterDescriptor, 2> parameters;",
        "    std::array<StateField, 2> state_fields;",
        "    uint8_t state_field_count;",
        "    InitializationDependency initialization_dependency;",
        "    const char* first_step_semantics;",
        "    bool legacy_state_dependency;",
        "    ResetMetadata reset;",
        "    SemanticProfile semantic_profile;",
        "    uint32_t semantic_version;",
        "    StrictExecutionStatus strict_execution;",
        "    VjpCapability vjp_capability;",
        "};",
        "",
        "struct ContinuousValue {",
        "    double value;",
        "};",
        "struct ChannelIndex {",
        "    std::size_t value;",
        "    explicit constexpr ChannelIndex(std::size_t v) : value(v) {}",
        "};",
        "struct DelayTicks {",
        "    uint64_t value;",
        "    explicit constexpr DelayTicks(uint64_t v) : value(v) {}",
        "};",
        "enum class MinMaxMode : uint8_t { Min = 0, Max = 1 };",
        "struct UnusedParameter {};",
        "using ParameterValue = std::variant<ContinuousValue, ChannelIndex, DelayTicks, MinMaxMode, UnusedParameter>;",
        "struct ContinuousParameterList {",
        "    std::array<ParameterSlot, 2> slots{};",
        "    uint8_t count = 0;",
        "};",
        "",
        "inline constexpr ParameterValue parameter_value_for_channel(ChannelIndex value) { return value; }",
        "inline constexpr ParameterValue parameter_value_for_delay(DelayTicks value) { return value; }",
        "inline constexpr ParameterValue parameter_value_for_continuous(ContinuousValue value) { return value; }",
        "",
        "inline std::span<const CellContract> all_cell_contracts();",
        "",
        "inline const CellContract* find_cell_contract(uint8_t code) {",
        "    for (const auto& contract : all_cell_contracts()) {",
        "        if (contract.code == code) return &contract;",
        "    }",
        "    return nullptr;",
        "}",
        "",
        "inline std::optional<std::reference_wrapper<const CellContract>> contract_for(CellType type) {",
        "    for (const auto& contract : all_cell_contracts()) {",
        "        if (contract.type == type) return std::cref(contract);",
        "    }",
        "    return std::nullopt;",
        "}",
        "",
        "inline std::optional<std::reference_wrapper<const CellContract>> contract_for_code(uint8_t code) {",
        "    if (const auto* contract = find_cell_contract(code)) return std::cref(*contract);",
        "    return std::nullopt;",
        "}",
        "",
        "inline std::optional<std::reference_wrapper<const CellContract>> contract_for_code(",
        "    uint8_t code, uint8_t profile_code) {",
        "    if (!semantic_profile_from_code(profile_code)) return std::nullopt;",
        "    return contract_for_code(code);",
        "}",
        "",
        "inline std::optional<std::reference_wrapper<const CellContract>> contract_for_code(",
        "    uint8_t code, SemanticProfile profile) {",
        "    return contract_for_code(code, static_cast<uint8_t>(profile));",
        "}",
        "",
        "inline StrictExecutionStatus strict_execution_status(const CellContract& contract) {",
        "    return contract.strict_execution;",
        "}",
        "",
        "inline bool is_continuous_trainable(const ParameterDescriptor& descriptor) {",
        "    return descriptor.kind == ParameterKind::Continuous && descriptor.trainable_continuous;",
        "}",
        "",
        "inline ContinuousParameterList continuous_trainable_parameters(const CellContract& contract) {",
        "    ContinuousParameterList result;",
        "    for (const auto& descriptor : contract.parameters) {",
        "        if (is_continuous_trainable(descriptor)) {",
        "            result.slots[result.count++] = descriptor.slot;",
        "        }",
        "    }",
        "    return result;",
        "}",
        "",
        "inline std::optional<ContinuousValue> make_continuous(",
        "    const ParameterDescriptor& descriptor, double value) {",
        "    if (descriptor.kind != ParameterKind::Continuous || !descriptor.finite_only ||",
        "        !std::isfinite(value)) {",
        "        return std::nullopt;",
        "    }",
        "    return ContinuousValue{value};",
        "}",
        "",
        "inline std::optional<ChannelIndex> make_channel_index(",
        "    const ParameterDescriptor& descriptor, std::size_t value) {",
        "    if (descriptor.kind != ParameterKind::ChannelIndex || descriptor.value_type != ParameterValueType::ChannelIndex) {",
        "        return std::nullopt;",
        "    }",
        "    return ChannelIndex{value};",
        "}",
        "",
        "inline std::optional<DelayTicks> make_delay_ticks(",
        "    const ParameterDescriptor& descriptor, int value) {",
        "    if (descriptor.kind != ParameterKind::DelayTicks || descriptor.value_type != ParameterValueType::DelayTicks ||",
        "        value < 1 || value > 16) {",
        "        return std::nullopt;",
        "    }",
        "    return DelayTicks{static_cast<uint64_t>(value)};",
        "}",
        "",
        "inline std::optional<MinMaxMode> make_min_max_mode(",
        "    const ParameterDescriptor& descriptor, MinMaxMode value) {",
        "    if (descriptor.kind != ParameterKind::Enum || descriptor.value_type != ParameterValueType::MinMaxMode) {",
        "        return std::nullopt;",
        "    }",
        "    if (value != MinMaxMode::Min && value != MinMaxMode::Max) return std::nullopt;",
        "    return value;",
        "}",
        "",
        "inline bool is_valid_min_max_mode(MinMaxMode value) {",
        "    return value == MinMaxMode::Min || value == MinMaxMode::Max;",
        "}",
        "",
        "inline bool parameter_value_matches(",
        "    const ParameterDescriptor& descriptor, const ParameterValue& value) {",
        "    // Intentional type-only check; validate_parameter checks domains and enum values.",
        "    switch (descriptor.value_type) {",
        "        case ParameterValueType::Continuous: return std::holds_alternative<ContinuousValue>(value);",
        "        case ParameterValueType::ChannelIndex: return std::holds_alternative<ChannelIndex>(value);",
        "        case ParameterValueType::DelayTicks: return std::holds_alternative<DelayTicks>(value);",
        "        case ParameterValueType::MinMaxMode: return std::holds_alternative<MinMaxMode>(value);",
        "        case ParameterValueType::Unused: return std::holds_alternative<UnusedParameter>(value);",
        "    }",
        "    return false;",
        "}",
        "",
        "inline bool validate_parameter(",
        "    const ParameterDescriptor& descriptor, const ParameterValue& value) {",
        "    switch (descriptor.value_type) {",
        "        case ParameterValueType::Continuous:",
        "            return std::holds_alternative<ContinuousValue>(value) &&",
        "                make_continuous(descriptor, std::get<ContinuousValue>(value).value).has_value();",
        "        case ParameterValueType::ChannelIndex:",
        "            return std::holds_alternative<ChannelIndex>(value) &&",
        "                descriptor.kind == ParameterKind::ChannelIndex;",
        "        case ParameterValueType::DelayTicks:",
        "            return std::holds_alternative<DelayTicks>(value) &&",
        "                std::get<DelayTicks>(value).value <= 16 &&",
        "                make_delay_ticks(descriptor, static_cast<int>(std::get<DelayTicks>(value).value)).has_value();",
        "        case ParameterValueType::MinMaxMode:",
        "            return std::holds_alternative<MinMaxMode>(value) &&",
        "                make_min_max_mode(descriptor, std::get<MinMaxMode>(value)).has_value();",
        "        case ParameterValueType::Unused:",
        "            return std::holds_alternative<UnusedParameter>(value) &&",
        "                descriptor.kind == ParameterKind::Unused;",
        "    }",
        "    return false;",
        "}",
        "",
        "inline const std::array<CellContract, %d> CELL_CONTRACTS = {{" % len(cells),
    ]

    for cell in cells:
        contract = cell["contract"]
        parameters = sorted(contract["parameters"], key=lambda parameter: parameter["slot"])
        parameter_literals = []
        for parameter in parameters:
            search_domain = parameter.get("search_domain")
            if isinstance(search_domain, dict) and "min" in search_domain:
                search_min = _cpp_float(search_domain["min"])
                search_max = _cpp_float(search_domain["max"])
                has_search_domain = "true"
            else:
                search_min = "0.0"
                search_max = "0.0"
                has_search_domain = "false"
            parameter_literals.append(
                "{" + ", ".join([
                    _cpp_string(parameter["name"]),
                    f"ParameterSlot::{parameter['slot'].title().replace('1', '1').replace('2', '2')}",
                    kind_enum[parameter["kind"]],
                    value_type_enum[parameter["value_type"]],
                    _cpp_string(parameter["legacy_mapping"]),
                    search_min, search_max, has_search_domain,
                    "true" if parameter["kind"] == "continuous" else "false",
                    "true" if parameter["trainable_continuous"] else "false",
                ]) + "}"
            )
        state_fields = [state_enum[field] for field in contract["state"]["fields"]]
        state_fields += ["StateField::StateValue"] * (2 - len(state_fields))
        reset = contract["reset"]
        reset_literal = "ResetMetadata{" + ", ".join(
            reset_enum[reset[field]]
            for field in (
                "state_value", "aux_state", "previous_input", "delay_buffer",
                "delay_index", "latch_state", "activation_count", "output_value",
            )
        ) + "}"
        strict_status = (
            "StrictExecutionStatus::Implemented"
            if contract.get("strict_execution") == "implemented"
            else "StrictExecutionStatus::Unsupported"
        )
        lines.append(
            "    {CellType::%s, %d, %s, %d, %s, %s, cell_type_to_sdsc_eval_op(CellType::%s), "
            "get_primitive_bounds(cell_type_to_sdsc_eval_op(CellType::%s)), %s, "
            "std::array<ParameterDescriptor, 2>{{%s}}, std::array<StateField, 2>{{%s}}, %d, %s, %s, %s, %s, "
            "SemanticProfile::%s, %d, %s, %s},"
            % (
                cell["name"], cell["code"], _cpp_string(cell["name"]),
                contract["inputs"]["count"], _cpp_string(contract["inputs"]["semantics"]),
                _cpp_string(contract["output"]), cell["name"], cell["name"],
                execution_policy_enum[contract["execution_policy"]],
                ", ".join(parameter_literals),
                ", ".join(state_fields), len(contract["state"]["fields"]),
                initialization_enum[contract["state"]["initialization"]],
                _cpp_string(contract["state"]["first_step"]),
                "true" if contract["state"]["legacy_dependency"] else "false",
                reset_literal,
                contract["semantic_profile"], contract["semantic_version"],
                strict_status,
                vjp_enum[contract["vjp_capability"]],
            )
        )

    lines.extend([
        "}};",
        "",
        "inline std::span<const CellContract> all_cell_contracts() {",
        "    return CELL_CONTRACTS;",
        "}",
        "",
        "} // namespace kun::core",
        "",
        "#endif /* KUN_CELLULAR_CORE_PRIMITIVE_CONTRACT_HPP_ */",
        "",
    ])
    return "\n".join(lines)

AUTO_GEN_BANNER_PY = """# ============================================================================
# THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
# FROM include/kun/cellular/ops.yaml.
# DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
# ============================================================================
"""

def generate_python_module(spec):
    prims = spec["sdsc_primitives"]
    cells = spec["cell_types"]

    lines = [
        '# -*- coding: utf-8 -*-',
        AUTO_GEN_BANNER_PY.strip(),
        '"""',
        'SDSCC Operator and Cell Type Definitions for Python (Forward & VJP)',
        '"""',
        'import math',
        'import numpy as np',
        '',
        'class SdscOp:',
    ]
    for p in prims:
        lines.append(f"    {p['name']} = {p['id']}")

    lines.extend([
        '',
        'class CellType:',
    ])
    for c in cells:
        lines.append(f"    {c['name']} = {c['code']}")

    lines.extend([
        '',
        'CELL_TYPE_TO_STR = {',
    ])
    for c in cells:
        lines.append(f"    CellType.{c['name']}: '{c['str_name']}',")
    lines.extend([
        '}',
        '',
        'STR_TO_CELL_TYPE = {v: k for k, v in CELL_TYPE_TO_STR.items()}',
        '',
        'PRIMITIVES_META = [',
    ])
    for p in prims:
        lines.append(f"    {{'id': {p['id']}, 'name': '{p['name']}', 'category': '{p['category']}', "
                     f"'has_state': {p['has_state']}, 'has_aux': {p['has_aux']}, "
                     f"'default_p1': {p['default_p1']}, 'default_p2': {p['default_p2']}, "
                     f"'lyapunov_bound': '{p['lyapunov_bound']}', "
                     f"'differentiable': {p.get('differentiable', True)}, "
                     f"'ste_gradient': '{p.get('ste_gradient', 'none')}', "
                     f"'bounds': {p.get('bounds', {})}}},")
    lines.append(']')
    lines.append('')
    return "\n".join(lines)

def main():
    parser = argparse.ArgumentParser(description="SDSCC Primitive Code Generator")
    parser.add_argument("--check", action="store_true", help="Check if generated files are up to date without writing")
    args = parser.parse_args()

    try:
        spec = load_ops_spec()
    except (TypeError, ValueError, KeyError, yaml.YAMLError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    c11_code = generate_c11_header(spec)
    c11_vjp_code = generate_c11_vjp_header(spec)
    cuda_code = generate_cuda_header(spec)
    cuda_vjp_code = generate_cuda_vjp_header(spec)
    cell_kernel_code = generate_cell_kernel_header(spec)
    cpp_code = generate_cpp_header(spec)
    py_code = generate_python_module(spec)
    contract_code = generate_contract_header(spec)

    targets = [
        (C11_OUT_PATH, c11_code),
        (C11_VJP_OUT_PATH, c11_vjp_code),
        (CUDA_OUT_PATH, cuda_code),
        (CUDA_VJP_OUT_PATH, cuda_vjp_code),
        (CELL_KERNEL_OUT_PATH, cell_kernel_code),
        (CPP_OUT_PATH, cpp_code),
        (PY_OUT_PATH, py_code),
        (CONTRACT_OUT_PATH, contract_code),
    ]

    if args.check:
        out_of_date = []
        for path, code in targets:
            if not os.path.exists(path):
                out_of_date.append((path, "File does not exist"))
                continue
            with open(path, "r", encoding="utf-8") as f:
                existing = f.read()
            if existing != code:
                out_of_date.append((path, "Content mismatch"))

        if out_of_date:
            print("ERROR: Generated operator files are OUT OF DATE with ops.yaml:")
            for p, reason in out_of_date:
                print(f"  - {os.path.relpath(p, REPO_ROOT)}: {reason}")
            print("Run 'python3 tools/gen_ops.py' to regenerate them.")
            sys.exit(1)
        else:
            print("SUCCESS: All operator headers match ops.yaml perfectly.")
            return 0

    # 写入生成文件
    for path, code in targets:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(code)
        print(f"[gen_ops] Generated: {os.path.relpath(path, REPO_ROOT)}")

    print("[gen_ops] Successfully generated all single-source-of-truth operator headers (Forward + VJP + Bounds)!")
    return 0

if __name__ == "__main__":
    sys.exit(main())
