# -*- coding: utf-8 -*-
# ============================================================================
# THIS FILE IS AUTOMATICALLY GENERATED BY tools/gen_ops.py
# FROM include/kun/cellular/ops.yaml.
# DO NOT EDIT DIRECTLY! ALL CHANGES MUST BE APPLIED TO ops.yaml!
# ============================================================================
"""
SDSCC Operator and Cell Type Definitions for Python
"""

class SdscOp:
    SDSC_OP_SENSE_0 = 0
    SDSC_OP_SENSE_1 = 1
    SDSC_OP_SENSE_2 = 2
    SDSC_OP_SENSE_3 = 3
    SDSC_OP_SUM = 4
    SDSC_OP_INTEGRATE = 5
    SDSC_OP_AMPLIFY = 6
    SDSC_OP_INVERT = 7
    SDSC_OP_DAMPER = 8
    SDSC_OP_CLIP = 9
    SDSC_OP_ABS = 10
    SDSC_OP_MULTIPLY = 11
    SDSC_OP_DIFF = 12
    SDSC_OP_SUB = 13
    SDSC_OP_RATIO = 14
    SDSC_OP_THRESHOLD = 15
    SDSC_OP_HYSTERESIS = 16
    SDSC_OP_DEADZONE = 17
    SDSC_OP_INHIBIT = 18
    SDSC_OP_AND = 19
    SDSC_OP_MIN_MAX = 20
    SDSC_OP_ACT_POS = 21
    SDSC_OP_ACT_NEG = 22
    SDSC_OP_ACT_RESET = 23
    SDSC_OP_CORRELATION = 24
    SDSC_OP_FATIGUE = 25
    SDSC_OP_PASSTHRU = 26

class CellType:
    SENSE_RAW_INPUT_0 = 0
    SENSE_RAW_INPUT_1 = 1
    SENSE_RAW_INPUT_2 = 2
    SENSE_RAW_INPUT_3 = 3
    SENSE_CHANNEL = 4
    OP_EMA = 10
    OP_DIFF = 11
    OP_INTEGRAL = 12
    OP_SUM = 13
    OP_SUB = 14
    OP_MULTIPLY = 15
    OP_RATIO = 16
    OP_ABS = 17
    OP_DELAY_N = 18
    OP_OSCILLATOR = 19
    OP_QUADRATIC = 20
    GATE_THRESHOLD = 24
    GATE_HYSTERESIS = 25
    GATE_AND = 26
    GATE_INHIBIT = 27
    GATE_DEADZONE = 28
    GATE_MIN_MAX = 29
    ACT_PRIMARY_POSITIVE = 30
    ACT_PRIMARY_NEGATIVE = 31
    ACT_DEFENSIVE_RESET = 32
    ACT_IMMUNE_BLOCK = 33
    ACT_CHANNEL = 34
    PREDICT_SENSE_0 = 40
    PREDICT_SENSE_1 = 41
    ASSOCIATION_HUB = 42

CELL_TYPE_TO_STR = {
    CellType.SENSE_RAW_INPUT_0: 'Sense_Input0',
    CellType.SENSE_RAW_INPUT_1: 'Sense_Input1',
    CellType.SENSE_RAW_INPUT_2: 'Sense_Input2',
    CellType.SENSE_RAW_INPUT_3: 'Sense_Input3',
    CellType.SENSE_CHANNEL: 'Sense_Channel',
    CellType.OP_EMA: 'Op_EMA',
    CellType.OP_DIFF: 'Op_Diff',
    CellType.OP_INTEGRAL: 'Op_Integral',
    CellType.OP_SUM: 'Op_Sum',
    CellType.OP_SUB: 'Op_Sub',
    CellType.OP_MULTIPLY: 'Op_Multiply',
    CellType.OP_RATIO: 'Op_Ratio',
    CellType.OP_ABS: 'Op_Abs',
    CellType.OP_DELAY_N: 'Op_DelayN',
    CellType.OP_OSCILLATOR: 'Op_Oscillator',
    CellType.OP_QUADRATIC: 'Op_Quadratic',
    CellType.GATE_THRESHOLD: 'Gate_Threshold',
    CellType.GATE_HYSTERESIS: 'Gate_Hysteresis',
    CellType.GATE_AND: 'Gate_And',
    CellType.GATE_INHIBIT: 'Gate_Inhibit',
    CellType.GATE_DEADZONE: 'Gate_Deadzone',
    CellType.GATE_MIN_MAX: 'Gate_MinMax',
    CellType.ACT_PRIMARY_POSITIVE: 'Act_PosAction',
    CellType.ACT_PRIMARY_NEGATIVE: 'Act_NegAction',
    CellType.ACT_DEFENSIVE_RESET: 'Act_DefReset',
    CellType.ACT_IMMUNE_BLOCK: 'Act_ImmuneLock',
    CellType.ACT_CHANNEL: 'Act_Channel',
    CellType.PREDICT_SENSE_0: 'Pred_Sense0',
    CellType.PREDICT_SENSE_1: 'Pred_Sense1',
    CellType.ASSOCIATION_HUB: 'Assoc_Hub',
}

STR_TO_CELL_TYPE = {v: k for k, v in CELL_TYPE_TO_STR.items()}

PRIMITIVES_META = [
    {'id': 0, 'name': 'SDSC_OP_SENSE_0', 'category': 'RECEPTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 1, 'name': 'SDSC_OP_SENSE_1', 'category': 'RECEPTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 1.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 2, 'name': 'SDSC_OP_SENSE_2', 'category': 'RECEPTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 2.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 3, 'name': 'SDSC_OP_SENSE_3', 'category': 'RECEPTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 3.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 4, 'name': 'SDSC_OP_SUM', 'category': 'METABOLIC', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 5, 'name': 'SDSC_OP_INTEGRATE', 'category': 'METABOLIC', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 6, 'name': 'SDSC_OP_AMPLIFY', 'category': 'METABOLIC', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 7, 'name': 'SDSC_OP_INVERT', 'category': 'METABOLIC', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 8, 'name': 'SDSC_OP_DAMPER', 'category': 'METABOLIC', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf] (asymptotically bounded)'},
    {'id': 9, 'name': 'SDSC_OP_CLIP', 'category': 'METABOLIC', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 10, 'name': 'SDSC_OP_ABS', 'category': 'METABOLIC', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[0.0, 1.0]'},
    {'id': 11, 'name': 'SDSC_OP_MULTIPLY', 'category': 'METABOLIC', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 12, 'name': 'SDSC_OP_DIFF', 'category': 'METABOLIC', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 13, 'name': 'SDSC_OP_SUB', 'category': 'METABOLIC', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 14, 'name': 'SDSC_OP_RATIO', 'category': 'METABOLIC', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-2.0, 2.0]'},
    {'id': 15, 'name': 'SDSC_OP_THRESHOLD', 'category': 'GATING', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 16, 'name': 'SDSC_OP_HYSTERESIS', 'category': 'GATING', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 17, 'name': 'SDSC_OP_DEADZONE', 'category': 'GATING', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 18, 'name': 'SDSC_OP_INHIBIT', 'category': 'GATING', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 19, 'name': 'SDSC_OP_AND', 'category': 'GATING', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[0.0, 1.0]'},
    {'id': 20, 'name': 'SDSC_OP_MIN_MAX', 'category': 'GATING', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 21, 'name': 'SDSC_OP_ACT_POS', 'category': 'EFFECTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[0.0, 1.0]'},
    {'id': 22, 'name': 'SDSC_OP_ACT_NEG', 'category': 'EFFECTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[0.0, 1.0]'},
    {'id': 23, 'name': 'SDSC_OP_ACT_RESET', 'category': 'EFFECTOR', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf]'},
    {'id': 24, 'name': 'SDSC_OP_CORRELATION', 'category': 'COGNITIVE', 'has_state': True, 'has_aux': True, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 25, 'name': 'SDSC_OP_FATIGUE', 'category': 'COGNITIVE', 'has_state': True, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-1.0, 1.0]'},
    {'id': 26, 'name': 'SDSC_OP_PASSTHRU', 'category': 'PASSTHRU', 'has_state': False, 'has_aux': False, 'default_p1': 1.0, 'default_p2': 0.0, 'lyapunov_bound': '[-inf, +inf]'},
]
